"""Export optimized weights to JSON and optionally TypeScript format."""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from .config import OUTPUT_DIR

logger = logging.getLogger(__name__)


def save_combo_result(
    geo_level: str,
    score_type: str,
    horizon: str,
    result: dict,
) -> Path:
    """Save result JSON for one score_type × horizon combo.

    File: output/{geo_level}/{score_type}_{horizon}.json
    """
    geo_dir = OUTPUT_DIR / geo_level
    geo_dir.mkdir(parents=True, exist_ok=True)

    filename = f"{score_type}_{horizon}.json"
    path = geo_dir / filename

    result["_meta"] = {
        "geo_level": geo_level,
        "score_type": score_type,
        "horizon": horizon,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "pipeline": "scoring_pipeline_v1",
    }

    with open(path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, default=str)

    logger.info("Saved: %s", path)
    return path


def save_feature_selection(geo_level: str, feature_data: dict) -> Path:
    """Save feature selection results for caching.

    File: output/{geo_level}/feature_selection.json
    """
    geo_dir = OUTPUT_DIR / geo_level
    geo_dir.mkdir(parents=True, exist_ok=True)

    path = geo_dir / "feature_selection.json"

    feature_data["_meta"] = {
        "geo_level": geo_level,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }

    with open(path, "w", encoding="utf-8") as f:
        json.dump(feature_data, f, indent=2, default=str)

    logger.info("Saved feature selection: %s", path)
    return path


def load_feature_selection(geo_level: str) -> dict | None:
    """Load cached feature selection if it exists."""
    path = OUTPUT_DIR / geo_level / "feature_selection.json"
    if path.exists():
        with open(path) as f:
            data = json.load(f)
        logger.info("Loaded cached feature selection: %s", path)
        return data
    return None


def combo_result_exists(geo_level: str, score_type: str, horizon: str) -> bool:
    """Check if a result file already exists for this combo."""
    path = OUTPUT_DIR / geo_level / f"{score_type}_{horizon}.json"
    return path.exists()


def clear_geo_output(geo_level: str) -> None:
    """Remove all output files for a geo level (for --force re-run)."""
    geo_dir = OUTPUT_DIR / geo_level
    if geo_dir.exists():
        import shutil
        shutil.rmtree(geo_dir)
        logger.info("Cleared output directory: %s", geo_dir)


def export_weights_summary(all_results: dict) -> Path:
    """Aggregate best weights across all geos into a single summary file.

    File: output/weights_summary.json
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUTPUT_DIR / "weights_summary.json"

    summary = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "pipeline": "scoring_pipeline_v1",
        "results": {},
    }

    for key, result in all_results.items():
        geo, score_type, horizon = key
        best = result.get("best_model", {})
        weights = result.get("weights", {})

        summary["results"][f"{geo}/{score_type}/{horizon}"] = {
            "model": best.get("model_name", "unknown"),
            "mean_ic": best.get("mean_ic", 0),
            "mean_quintile_spread": best.get("mean_quintile_spread", 0),
            "mean_hit_rate": best.get("mean_hit_rate", 0),
            "weights": weights.get("weights", {}),
        }

    with open(path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, default=str)

    logger.info("Saved weights summary: %s", path)
    return path


def generate_typescript_weights(all_results: dict) -> str:
    """Generate TypeScript code for formula-weights.ts format.

    Returns the TS source code as a string (does not write to file).
    """
    lines = [
        "// Auto-generated by scoring_pipeline — do not edit manually",
        f"// Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "export interface FormulaWeight {",
        "  weight: number;",
        "  direction: 1 | -1;",
        "}",
        "",
        "export interface FormulaWeights {",
        "  [metric: string]: FormulaWeight;",
        "}",
        "",
    ]

    for key, result in sorted(all_results.items()):
        geo, score_type, horizon = key
        weights = result.get("weights", {}).get("weights", {})
        if not weights:
            continue

        var_name = f"{score_type}_{geo}_{horizon}_weights".upper()
        lines.append(f"export const {var_name}: FormulaWeights = {{")
        for feat, w in sorted(weights.items(), key=lambda x: x[1]["weight"], reverse=True):
            lines.append(f'  {feat}: {{ weight: {w["weight"]}, direction: {w["direction"]} }},')
        lines.append("};")
        lines.append("")

    return "\n".join(lines)
