export interface RealtorNationalRecord {
    period_date: Date;
    country: string;
    median_listing_price: number | null;
    median_listing_price_mm: number | null;
    median_listing_price_yy: number | null;
    active_listing_count: number | null;
    active_listing_count_mm: number | null;
    active_listing_count_yy: number | null;
    median_days_on_market: number | null;
    median_days_on_market_mm: number | null;
    median_days_on_market_yy: number | null;
    new_listing_count: number | null;
    new_listing_count_mm: number | null;
    new_listing_count_yy: number | null;
    price_increased_count: number | null;
    price_increased_count_mm: number | null;
    price_increased_count_yy: number | null;
    price_increased_share: number | null;
    price_increased_share_mm: number | null;
    price_increased_share_yy: number | null;
    price_reduced_count: number | null;
    price_reduced_count_mm: number | null;
    price_reduced_count_yy: number | null;
    price_reduced_share: number | null;
    price_reduced_share_mm: number | null;
    price_reduced_share_yy: number | null;
    pending_listing_count: number | null;
    pending_listing_count_mm: number | null;
    pending_listing_count_yy: number | null;
    median_listing_price_per_square_foot: number | null;
    median_listing_price_per_square_foot_mm: number | null;
    median_listing_price_per_square_foot_yy: number | null;
    median_square_feet: number | null;
    median_square_feet_mm: number | null;
    median_square_feet_yy: number | null;
    average_listing_price: number | null;
    average_listing_price_mm: number | null;
    average_listing_price_yy: number | null;
    total_listing_count: number | null;
    total_listing_count_mm: number | null;
    total_listing_count_yy: number | null;
    pending_ratio: number | null;
    pending_ratio_mm: number | null;
    pending_ratio_yy: number | null;
    quality_flag: number;
}

export interface RealtorStateRecord {
    period_date: Date;
    state_name: string;
    state_id: string;
    median_listing_price: number | null;
    median_listing_price_mm: number | null;
    median_listing_price_yy: number | null;
    active_listing_count: number | null;
    active_listing_count_mm: number | null;
    active_listing_count_yy: number | null;
    median_days_on_market: number | null;
    median_days_on_market_mm: number | null;
    median_days_on_market_yy: number | null;
    new_listing_count: number | null;
    new_listing_count_mm: number | null;
    new_listing_count_yy: number | null;
    price_increased_count: number | null;
    price_increased_count_mm: number | null;
    price_increased_count_yy: number | null;
    price_increased_share: number | null;
    price_increased_share_mm: number | null;
    price_increased_share_yy: number | null;
    price_reduced_count: number | null;
    price_reduced_count_mm: number | null;
    price_reduced_count_yy: number | null;
    price_reduced_share: number | null;
    price_reduced_share_mm: number | null;
    price_reduced_share_yy: number | null;
    pending_listing_count: number | null;
    pending_listing_count_mm: number | null;
    pending_listing_count_yy: number | null;
    median_listing_price_per_square_foot: number | null;
    median_listing_price_per_square_foot_mm: number | null;
    median_listing_price_per_square_foot_yy: number | null;
    median_square_feet: number | null;
    median_square_feet_mm: number | null;
    median_square_feet_yy: number | null;
    average_listing_price: number | null;
    average_listing_price_mm: number | null;
    average_listing_price_yy: number | null;
    total_listing_count: number | null;
    total_listing_count_mm: number | null;
    total_listing_count_yy: number | null;
    pending_ratio: number | null;
    pending_ratio_mm: number | null;
    pending_ratio_yy: number | null;
    quality_flag: number;
}

export interface RealtorCombinedRecord {
    period_date: Date;
    cbsa_code?: string;
    cbsa_title?: string;
    county_fips?: string;
    county_name?: string;
    postal_code?: string;
    zip_name?: string;
    household_rank?: number | null;
    hotness_rank?: number | null;
    hotness_rank_mm?: number | null;
    hotness_rank_yy?: number | null;
    hotness_score?: number | null;
    supply_score?: number | null;
    demand_score?: number | null;
    median_listing_price: number | null;
    median_listing_price_mm: number | null;
    median_listing_price_yy: number | null;
    median_listing_price_vs_us?: number | null;
    active_listing_count: number | null;
    active_listing_count_mm: number | null;
    active_listing_count_yy: number | null;
    median_days_on_market: number | null;
    median_days_on_market_mm: number | null;
    median_days_on_market_yy: number | null;
    median_dom_vs_us?: number | null;
    new_listing_count: number | null;
    new_listing_count_mm: number | null;
    new_listing_count_yy: number | null;
    price_increased_count: number | null;
    price_increased_count_mm: number | null;
    price_increased_count_yy: number | null;
    price_increased_share: number | null;
    price_increased_share_mm: number | null;
    price_increased_share_yy: number | null;
    price_reduced_count: number | null;
    price_reduced_count_mm: number | null;
    price_reduced_count_yy: number | null;
    price_reduced_share: number | null;
    price_reduced_share_mm: number | null;
    price_reduced_share_yy: number | null;
    pending_listing_count: number | null;
    pending_listing_count_mm: number | null;
    pending_listing_count_yy: number | null;
    median_listing_price_per_square_foot: number | null;
    median_listing_price_per_square_foot_mm: number | null;
    median_listing_price_per_square_foot_yy: number | null;
    median_square_feet: number | null;
    median_square_feet_mm: number | null;
    median_square_feet_yy: number | null;
    average_listing_price: number | null;
    average_listing_price_mm: number | null;
    average_listing_price_yy: number | null;
    total_listing_count: number | null;
    total_listing_count_mm: number | null;
    total_listing_count_yy: number | null;
    pending_ratio: number | null;
    pending_ratio_mm: number | null;
    pending_ratio_yy: number | null;
    page_view_count_per_property_mm?: number | null;
    page_view_count_per_property_yy?: number | null;
    page_view_count_per_property_vs_us?: number | null;
    quality_flag: number;
}
