/**
 * Visual regression for the /analyzer page (Phase 1F.1).
 *
 * Captures a full-page screenshot at three viewports (desktop / tablet / mobile)
 * after the user lands on the analyzer, fills an address, and the KPI strip +
 * charts render. The first run generates baselines under
 * `__snapshots__/analyzer-charts.spec.ts-snapshots/` next to this file.
 *
 * Prerequisites for baseline capture (run locally, NOT in CI for the first cut):
 *   1. Backend running on :3001 with `NODE_OPTIONS=--use-system-ca` so RentCast
 *      TLS works under Norton AV (per `[[reference_norton-ca-node-tls]]`).
 *   2. Frontend dev server running on :3000.
 *   3. Auth fixture present at `tests/fixtures/.auth/enterprise-user.json` —
 *      generated by `npx playwright test --project=setup` with TEST_*_USER env
 *      vars set (see `tests/e2e/auth.setup.ts`).
 *   4. `npx playwright test analyzer-charts --update-snapshots` to write baselines.
 *
 * Stability notes:
 *   - The desktop viewport is the primary baseline; tablet/mobile catch responsive
 *     regressions in `KPIStrip` collapse and `InputPanel` accordion behavior.
 *   - `maxDiffPixelRatio: 0.02` tolerates minor font + chart anti-aliasing diffs
 *     across machines. Tighten if false positives become a problem.
 *   - Charts derive from input values, which derive from RentCast. If the upstream
 *     returns different numbers for the test address on a given day, the charts
 *     will shift — re-baseline rather than chase pixel diffs.
 */

import { test, expect } from "@playwright/test";
import path from "path";

const enterpriseUserAuthFile = path.join(
  __dirname,
  "../../fixtures/.auth/enterprise-user.json",
);

const VIEWPORTS = [
  { name: "desktop", width: 1440, height: 900 },
  { name: "tablet", width: 800, height: 1024 },
  { name: "mobile", width: 390, height: 844 },
];

test.describe("/analyzer visual regression", () => {
  test.use({ storageState: enterpriseUserAuthFile });

  for (const vp of VIEWPORTS) {
    test(`analyzer renders consistently at ${vp.name}`, async ({ page }) => {
      await page.setViewportSize({ width: vp.width, height: vp.height });
      await page.goto("/analyzer");

      // Reuse the same selector chain as the functional analyzer.spec.ts so
      // the UI must reach an analyzed state — not just a blank page — before
      // we screenshot. KPI strip headers render once input values exist.
      await page
        .getByRole("textbox", { name: /Address search/i })
        .fill("123 Main St Austin");
      await page
        .getByText(/Austin, TX/)
        .first()
        .click();

      await expect(page.getByText("Cap rate", { exact: true })).toBeVisible({
        timeout: 15_000,
      });

      // Wait for at least one chart to actually mount. Recharts emits
      // `.recharts-line` (MultiLineChart) and the D3 WaterfallChart emits
      // `[data-waterfall-bar]` — either presence proves charts hydrated.
      await page.waitForSelector(".recharts-line, [data-waterfall-bar]", {
        timeout: 15_000,
      });

      expect(await page.screenshot({ fullPage: true })).toMatchSnapshot(
        `analyzer-${vp.name}.png`,
        { maxDiffPixelRatio: 0.02 },
      );
    });
  }
});
