// Thin wrapper around the auto-generated JSON data file.
// The raw data lives in county-slug-data.json (generated by scripts/generate-county-slugs.ts
// or scripts/process-county-data.js).
// Do not edit the JSON file manually — re-run the script to update.

import type { CountySlugEntry } from "./county-slugs";
import rawData from "./county-slug-data.json";
import { makeLazyMap } from "./lazy-map";

export const COUNTY_SLUG_DATA: CountySlugEntry[] = rawData;

/** Map from slug to county entry for O(1) lookup. Built lazily on first access. */
export const SLUG_TO_COUNTY = makeLazyMap<string, CountySlugEntry>(
  () => new Map(COUNTY_SLUG_DATA.map((e) => [e.slug, e])),
);

/** Map from FIPS code to county entry for O(1) lookup. Built lazily on first access. */
export const FIPS_TO_COUNTY = makeLazyMap<string, CountySlugEntry>(
  () => new Map(COUNTY_SLUG_DATA.map((e) => [e.fips, e])),
);
