// Thin wrapper around the auto-generated JSON data file.
// The raw data lives in metro-slug-data.json (generated by scripts/generate-metro-slugs.ts).
// Do not edit the JSON file manually — re-run the script to update.

import type { MetroSlugEntry } from "./metro-slugs";
import rawData from "./metro-slug-data.json";
import { makeLazyMap } from "./lazy-map";

export const METRO_SLUG_DATA: MetroSlugEntry[] = rawData;

/** Map from slug to metro entry for O(1) lookup. Built lazily on first access. */
export const SLUG_TO_METRO = makeLazyMap<string, MetroSlugEntry>(
  () => new Map(METRO_SLUG_DATA.map((e) => [e.slug, e])),
);

/** Map from CBSA code to metro entry for O(1) lookup. Built lazily on first access. */
export const CBSA_TO_METRO = makeLazyMap<string, MetroSlugEntry>(
  () => new Map(METRO_SLUG_DATA.map((e) => [e.cbsaCode, e])),
);
