// Thin wrapper around the auto-generated JSON data file.
// The raw data lives in zip-slug-data.json (generated by scripts/generate-zip-slugs.ts).
// Do not edit the JSON file manually — re-run the script to update.

import type { ZipSlugEntry } from "./zip-slugs";
import rawData from "./zip-slug-data.json";

export const ZIP_SLUG_DATA: ZipSlugEntry[] = rawData;

/** Map from slug to ZIP entry for O(1) lookup */
export const SLUG_TO_ZIP = new Map<string, ZipSlugEntry>(
  ZIP_SLUG_DATA.map((e) => [e.slug, e]),
);

/** Map from ZIP code to ZIP entry for O(1) lookup */
export const ZIP_TO_ENTRY = new Map<string, ZipSlugEntry>(
  ZIP_SLUG_DATA.map((e) => [e.zip, e]),
);
