/**
 * METRIC-GEOGRAPHY AVAILABILITY MAPPING
 *
 * This file is auto-generated by verify-metric-geography-availability.ts
 * DO NOT EDIT MANUALLY - run the verification script to regenerate.
 *
 * Maps each metric to the geography levels where data is actually available.
 * Used by the metric selector to disable unavailable combinations.
 *
 * Updated with database verification for metrics marked unavailable by API.
 */

import type { GeoLevel } from './metrics';

export type MetricAvailabilityMap = {
  [metricId: string]: {
    [geoLevel in GeoLevel]?: boolean;
  };
};

/**
 * Availability mapping: metricId -> geoLevel -> available
 * true = data is available, false/undefined = data is not available
 */
export const METRIC_GEO_AVAILABILITY: MetricAvailabilityMap = {
  affordable_home_price: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  cap_rate: {
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  cost_of_living: {
    state: true,
    metro: true,
    tract: true,
  },
  days_on_market: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  demand_score: {
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  for_sale_inventory: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  gdp_growth: {
    state: true,
    metro: true,
    county: true,
    tract: true,
  },
  grm: {
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  gross_yield: {
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  home_sales: {
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  home_sales_yoy: {
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  home_value: {
    national: true,
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
    tract: true,
  },
  home_value_5yr: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  home_value_mom: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  home_value_yoy: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  homeowner_affordability: {
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
  },
  homeownership_rate: {
    national: true,
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
    tract: true,
  },
  homeready_score: {
    metro: true,
    county: true,
    zip: true,
  },
  hotness_score: {
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  income_growth: {
    national: true,
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
    tract: true,
  },
  income_to_buy: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  income_to_rent: {
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
  },
  inventory_surplus: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  inventory_yoy: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  investment_score: {
  },
  investoredge_score: {
    metro: true,
    county: true,
    zip: true,
  },
  job_growth: {
    national: true,
    state: true,
    metro: true,
    county: true,
    tract: true,
  },
  listing_price: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  long_term_growth_score: {
  },
  market_health_score: {
    metro: true,
    county: true,
    zip: true,
  },
  market_heat: {
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
    tract: true,
  },
  median_age: {
    national: true,
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
    tract: true,
  },
  median_income: {
    national: true,
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
    tract: true,
  },
  mf_permits: {
    national: true,
    state: true,
    county: true,
  },
  new_construction_ppsf: {
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
  },
  new_construction_price: {
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
  },
  new_construction_sales: {
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
    tract: true,
  },
  new_listings: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  new_listings_yoy: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  overvalued_pct: {
    metro: true,
  },
  pending_listings: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  pending_ratio: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  permit_value_per_unit: {
    national: true,
    state: true,
    county: true,
  },
  permits_yoy: {
    national: true,
    state: true,
    county: true,
  },
  population: {
    national: true,
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
    tract: true,
  },
  population_growth: {
    national: true,
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
    tract: true,
  },
  price_cut_pct: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  price_increase_pct: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  price_per_sqft: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  rent_for_houses: {
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
    tract: true,
  },
  rent_index: {
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
    tract: true,
  },
  rent_to_price_ratio: {
  },
  renter_affordability: {
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
  },
  sale_to_list: {
    state: true,
    metro: true,
    county: true,
    city: true,
    zip: true,
    tract: true,
  },
  sf_mf_ratio: {
    national: true,
    state: true,
    county: true,
  },
  sf_permits: {
    national: true,
    state: true,
    county: true,
  },
  supply_score: {
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
  total_permits: {
    national: true,
    state: true,
    county: true,
  },
  unemployment_rate: {
    national: true,
    state: true,
    metro: true,
    county: true,
    tract: true,
  },
  years_to_save: {
    national: true,
    state: true,
    metro: true,
    county: true,
    zip: true,
    tract: true,
  },
};

/**
 * Check if a metric has data available for a given geography level
 */
export function isMetricAvailableForGeo(
  metricId: string,
  geoLevel: GeoLevel
): boolean {
  const metricAvailability = METRIC_GEO_AVAILABILITY[metricId];
  if (!metricAvailability) return false;
  
  // National level uses state data
  if (geoLevel === 'national') {
    return metricAvailability.state === true;
  }
  
  return metricAvailability[geoLevel] === true;
}