/**
 * Custom Report V2 Sections
 *
 * Custom reports have a hybrid structure: 2 fixed sections (executive
 * summary + scenario analysis) are always present, while middle sections
 * are dynamically generated by the outline pass based on the user's
 * specific question.
 *
 * Exports:
 * - CUSTOM_REPORT_FIXED_SECTIONS — the 2 always-present sections
 * - buildCustomSectionPrompt() — constructs a NarrativePromptConfig
 *   from an outline-generated section definition
 */

import type { NarrativePromptConfig } from '../narrative-prompt-shared';

/** Section definition generated by the outline pass. */
export interface CustomSectionDefinition {
  /** Unique section ID (e.g., "affordability_deep_dive"). */
  id: string;
  /** Human-readable section title. */
  title: string;
  /** What this section should analyze — generated by the outline AI. */
  analysis_focus: string;
  /** Which template variables are most relevant to this section. */
  relevant_vars: string[];
  /** Suggested max tokens for this section. */
  suggested_tokens: number;
}

export const CUSTOM_REPORT_FIXED_SECTIONS: Record<
  string,
  NarrativePromptConfig
> = {
  executive_summary: {
    prompt_template: `You are writing the executive summary for a custom market analysis of {{geography_name}}.

## The Question
{{custom_question}}

{{#if outline}}
## Report Outline
{{outline}}
{{/if}}

## Market Snapshot
- ZHVI: {{zhvi}} | YoY: {{zhvi_yoy}}%
- ZORI: {{zori}} | YoY: {{zori_yoy}}%
- Days on market: {{days_on_market}}
- Market phase: {{market_phase}}
- Median income: {{median_household_income}}
{{#if homeready_score}}- HomeReady: {{homeready_score}}/100{{/if}}
{{#if investoredge_score}}- InvestorEdge: {{investoredge_score}}/100{{/if}}
- Market Health: {{markethealth_score}}/100

Write 2-3 paragraphs that directly answer the user's question at a high level. This is the executive summary — detailed analysis follows in subsequent sections.

The summary should:
1. Directly address the specific question asked
2. Provide a clear, data-backed answer (not "it depends")
3. Preview the key insights that the rest of the report will explore

Rules:
- Answer the question first, then provide context
- Reference at least 3 specific data points
- Do NOT give a generic market overview — stay focused on the question
- If the question is ambiguous, interpret it in the most useful way`,
    max_tokens: 1500,
    output_format: 'text',
  },

  scenario_analysis: {
    prompt_template: `You are writing the closing scenario analysis for a custom report on {{geography_name}}.

## The Question
{{custom_question}}

{{#if outline}}
## Report Outline (this is the closing section)
{{outline}}
{{/if}}

## Key Metrics
- Market phase: {{market_phase}}
- ZHVI YoY: {{zhvi_yoy}}% | Forecast: {{zhvf_1yr_pct}}%
- Appreciation trajectory: {{appreciation_trajectory}}
- Downside scenario: {{downside_scenario}}
- Unemployment: {{unemployment_rate}}%

Write 2-3 paragraphs covering:
1. **Most likely outcome** related to the user's question over the next 6-12 months
2. **What could go better** — upside scenario with trigger conditions
3. **What could go worse** — downside scenario with trigger conditions

Then provide a clear, actionable recommendation tied to the original question.

Rules:
- Scenarios must be specific to the question asked, not generic market outlook
- Quantify outcomes where data supports it
- The recommendation must be decisive and actionable`,
    max_tokens: 1200,
    output_format: 'text',
  },
};

/**
 * Build a NarrativePromptConfig for a dynamically-defined custom section.
 *
 * The outline pass generates section definitions describing what each
 * middle section should analyze. This function wraps that definition
 * into a prompt template the AI can execute.
 */
export function buildCustomSectionPrompt(
  sectionDef: CustomSectionDefinition,
  context: { customQuestion: string },
): NarrativePromptConfig {
  const varsBlock = sectionDef.relevant_vars
    .map((v) => `- {{${v}}}`)
    .join('\n');

  return {
    prompt_template: `You are writing the "${sectionDef.title}" section of a custom market analysis for {{geography_name}}.

## The Question
${context.customQuestion}

## Section Focus
${sectionDef.analysis_focus}

{{#if outline}}
## Report Outline (maintain coherence)
{{outline}}
{{/if}}

## Relevant Data
${varsBlock}

## Additional Context
- Market phase: {{market_phase}}
- Overall score: {{overall_score}}/100
{{#if news_context}}
## Market Intelligence
{{news_context}}
{{/if}}

Write 3-5 paragraphs analyzing the focus area described above. Ground every claim in specific data from the relevant metrics. Connect your analysis back to the user's original question.

Rules:
- Stay focused on the section topic — do NOT write a general market overview
- Reference at least 3 specific data points
- Each paragraph must advance the analysis, not repeat prior sections
- If news is relevant to this section's focus, weave it in naturally`,
    max_tokens: Math.min(sectionDef.suggested_tokens, 3000),
    output_format: 'text',
  };
}
