/**
 * Tour aha-finale E2E — authenticated report-as-finale + Connect Claude hero
 *
 * Drives the repurposed /tour?phase=step4 finale (`Step4Aha`) for an
 * authenticated user and proves two things the unit tests cannot (they run in
 * jsdom with mocked auth + a mocked report mutation):
 *
 *   1. The finale renders the real listing-presentation report WITHOUT the
 *      "Demo report" watermark — for an authed user `Step4Aha` passes
 *      `showWatermark={false}`, so the demo banner must be absent.
 *   2. The persona springboard leads with the Connect-Claude hero (the
 *      Claude/MCP differentiator), a link to /docs/mcp.
 *
 * Session hydration: `useTourSession` reads `phase`, `persona`, and `market`
 * straight off the URL search params (see useTourSession.ts), so loading
 * `/tour?phase=step4&persona=investor&market=metro-39580` drops the finale into
 * the success path with no prior persona/market selection state required. The
 * sessionId is minted from a cookie/storage if the URL one is absent — the
 * finale only needs *a* valid sessionId, not the URL one — so the report call
 * fires regardless.
 *
 * Auth: /tour lives behind the authenticated app shell. We reuse the
 * enterprise-user storage state (regenerated by the `setup` project) exactly
 * like tour-spotlight.spec.ts — an authenticated user is all the finale's
 * `authed` branch needs.
 *
 * Prerequisites:
 * - Frontend dev server on :3000, backend on :3001
 * - Run against LOCAL: PLAYWRIGHT_BASE_URL=http://localhost:3000
 *   (.env.test defaults to prod, so the override is mandatory.)
 */

import { test, expect } from "@playwright/test";
import path from "path";

const authFile = path.join(__dirname, "../fixtures/.auth/enterprise-user.json");

// The finale generates a report via a real backend call (anon
// listing-presentation), so allow generous time for the round-trip + render.
test.setTimeout(60_000);

// The authed finale now drives the report through the JWT-guarded
// `/api/anonymous/listing-presentation/authenticated` endpoint: NO anon
// rate-limit (so repeat runs don't 429), NO bot-UA block (so Playwright's UA
// passes), and the market name is resolved server-side from (geoLevel, geoId)
// — so a bare-URL market like `metro-39580` no longer 400s the report DTO.
// VERIFIED: the endpoint returns 201 with a full 10-section report (curl + the
// Playwright trace both confirm the fetch succeeds).
//
// The report-render contract is now fixed: `ListingPresentation` runs each
// backend section's `data` through `listing-sections/adapt-sections.ts`, which
// maps the real shapes → component props and degrades empty/mismatched sections
// to limitedData instead of crashing. Covered at the unit level by
// ListingPresentation.realrender.test.tsx (real components against real shapes).
test.describe("Tour aha finale", () => {
  test.use({ storageState: authFile });

  // Boise metro (CBSA 39580) — a market with real PropertyIQ data.
  const FINALE_URL =
    "/tour?phase=step4&persona=investor&market=metro-39580&sessionId=e2e";

  test("authenticated finale shows the unwatermarked report + Connect Claude hero", async ({
    page,
  }) => {
    await page.goto(FINALE_URL, { waitUntil: "load" });

    // The finale only renders once authenticated; if auth failed we'd be on the
    // sign-in page and this would fail fast with a clear message.
    expect(page.url(), "should not have redirected to sign-in").not.toMatch(
      /\/auth\/sign-in/,
    );

    // The report resolves via a live backend call; the persona springboard is
    // rendered alongside the report only on the success branch. Waiting for the
    // hero to appear waits out the whole loading → success transition.
    const connectClaude = page.getByRole("link", {
      name: /Connect Claude/i,
    });
    await expect(connectClaude).toBeVisible({ timeout: 45_000 });
    await expect(connectClaude).toHaveAttribute("href", "/docs/mcp");

    // Authed users get the full report unwatermarked — the demo banner that the
    // anonymous path shows (ListingPresentation `showWatermark`) must be absent.
    await expect(page.getByText(/Demo report/i)).toHaveCount(0);

    // The springboard section itself is present (belt-and-suspenders).
    await expect(
      page.locator('[data-testid="persona-springboard"]'),
    ).toBeVisible();
  });
});
