/**
 * Tour spotlight E2E — crisp target + dismiss-into-app
 *
 * Drives the live sandbox tour on /map?tour=step1 and proves two things the
 * unit tests cannot (they run in jsdom with no real compositing/layout):
 *
 *   1. The highlighted search bar is NOT covered by any dim/blur panel — the
 *      four `spotlight-dim-*` panels tile AROUND the target rect, leaving it
 *      crisp. We verify this with elementFromPoint at the target's center.
 *   2. Dismissing the tour lands inside the app (/dashboard), never the
 *      marketing home (`/`).
 *
 * Auth: /map lives behind the authenticated app shell, so an unauthenticated
 * visit redirects to sign-in and the spotlight never renders. We reuse the
 * enterprise-user storage state (regenerated by the `setup` project) exactly
 * like onboarding-conversion.spec.ts.
 *
 * Prerequisites:
 * - Frontend dev server on :3000, backend on :3001
 * - Run against LOCAL: PLAYWRIGHT_BASE_URL=http://localhost:3000
 *
 * Desktop-only: the dim-panel geometry + ConnectedTooltip path is the desktop
 * surface. On a mobile viewport the page renders TourBottomSheet instead, which
 * is covered by its own unit test, so we skip there to keep this deterministic.
 */

import { test, expect } from "@playwright/test";
import path from "path";

const authFile = path.join(__dirname, "../fixtures/.auth/enterprise-user.json");

// Loads live data + waits for the spotlight poll/animation to settle.
test.setTimeout(45_000);

test.describe("Tour spotlight", () => {
  test.use({ storageState: authFile });

  // Boise metro (CBSA 39580) — a market with real PropertyIQ data.
  const TOUR_URL =
    "/map?tour=step1&persona=investor&market=metro-39580&sessionId=e2e-test";

  // Desktop surface only — mobile renders the bottom sheet (separate unit test).
  test.skip(
    ({ viewport }) => !!viewport && viewport.width < 768,
    "Desktop spotlight surface only",
  );

  test("highlighted target is not covered by a dim/blur panel", async ({
    page,
  }) => {
    await page.goto(TOUR_URL, { waitUntil: "load" });

    // The tour only renders once authenticated; if auth failed we'd be on the
    // sign-in page and this would fail fast with a clear message.
    expect(page.url(), "should not have redirected to sign-in").not.toMatch(
      /\/auth\/sign-in/,
    );

    const target = page.locator('[data-tour="search-bar"]').first();
    await expect(target).toBeVisible({ timeout: 15_000 });

    // Wait for the spotlight to actually composite (the four panels mount only
    // after BreathingSpotlight measures the target). If this never appears, the
    // spotlight didn't render — a real failure, not a flake.
    await expect(page.locator('[data-testid="spotlight-dim-top"]')).toBeVisible(
      { timeout: 15_000 },
    );

    const box = await target.boundingBox();
    expect(box).not.toBeNull();
    const cx = box!.x + box!.width / 2;
    const cy = box!.y + box!.height / 2;

    // The element at the target's center must NOT be a dim panel — proves the
    // cutout is real and the search bar is crisp (uncovered).
    const onTopIsDim = await page.evaluate(
      ([x, y]) => {
        const el = document.elementFromPoint(x as number, y as number);
        return !!el?.closest('[data-testid^="spotlight-dim-"]');
      },
      [cx, cy],
    );
    expect(
      onTopIsDim,
      "target center is covered by a spotlight dim panel (cutout is broken)",
    ).toBe(false);

    // No legacy full-screen blur overlay exists.
    await expect(
      page.locator('[data-testid="spotlight-fullscreen-blur"]'),
    ).toHaveCount(0);
  });

  test("dismiss returns into the app, not the marketing home", async ({
    page,
  }) => {
    await page.goto(TOUR_URL, { waitUntil: "load" });

    expect(page.url(), "should not have redirected to sign-in").not.toMatch(
      /\/auth\/sign-in/,
    );

    // The tooltip (role=dialog) must be up before we exit the tour.
    const tooltip = page.getByRole("dialog", {
      name: /you picked your market/i,
    });
    await expect(tooltip).toBeVisible({ timeout: 15_000 });

    // "Do this later" is the only control wired to dismiss() (-> /dashboard).
    // It is gated behind a 10s grace timer inside ConnectedTooltip, and that
    // timer restarts on every re-render. The live map churns while its data
    // loads, so we wait for the network to go idle first to stop the churn,
    // then wait generously for the button to surface.
    await page
      .waitForLoadState("networkidle", { timeout: 20_000 })
      .catch(() => {});

    const dismissButton = page.getByRole("button", { name: /do this later/i });
    await dismissButton.waitFor({ state: "visible", timeout: 25_000 });
    await dismissButton.click();

    // dismiss() -> router.push("/dashboard"): we exit the tour INTO the app,
    // never the marketing home (`/`) and never bounced to sign-in.
    await page.waitForURL(/\/dashboard(\?|$)/, { timeout: 10_000 });
    const { pathname } = new URL(page.url());
    expect(pathname, "dismiss must land on /dashboard").toBe("/dashboard");
    expect(pathname, "must not land on the marketing home").not.toBe("/");
  });
});
