ALTER TABLE market_time_series_2000 DROP CONSTRAINT IF EXISTS market_time_series_2000_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2001 DROP CONSTRAINT IF EXISTS market_time_series_2001_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2002 DROP CONSTRAINT IF EXISTS market_time_series_2002_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2003 DROP CONSTRAINT IF EXISTS market_time_series_2003_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2004 DROP CONSTRAINT IF EXISTS market_time_series_2004_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2005 DROP CONSTRAINT IF EXISTS market_time_series_2005_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2006 DROP CONSTRAINT IF EXISTS market_time_series_2006_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2007 DROP CONSTRAINT IF EXISTS market_time_series_2007_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2008 DROP CONSTRAINT IF EXISTS market_time_series_2008_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2009 DROP CONSTRAINT IF EXISTS market_time_series_2009_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2010 DROP CONSTRAINT IF EXISTS market_time_series_2010_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2011 DROP CONSTRAINT IF EXISTS market_time_series_2011_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2012 DROP CONSTRAINT IF EXISTS market_time_series_2012_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2013 DROP CONSTRAINT IF EXISTS market_time_series_2013_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2014 DROP CONSTRAINT IF EXISTS market_time_series_2014_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2015 DROP CONSTRAINT IF EXISTS market_time_series_2015_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2016 DROP CONSTRAINT IF EXISTS market_time_series_2016_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2017 DROP CONSTRAINT IF EXISTS market_time_series_2017_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2018 DROP CONSTRAINT IF EXISTS market_time_series_2018_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2019 DROP CONSTRAINT IF EXISTS market_time_series_2019_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2020 DROP CONSTRAINT IF EXISTS market_time_series_2020_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2021 DROP CONSTRAINT IF EXISTS market_time_series_2021_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2022 DROP CONSTRAINT IF EXISTS market_time_series_2022_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2023 DROP CONSTRAINT IF EXISTS market_time_series_2023_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2024 DROP CONSTRAINT IF EXISTS market_time_series_2024_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2025 DROP CONSTRAINT IF EXISTS market_time_series_2025_region_id_date_metric_name_data_sou_key;
ALTER TABLE market_time_series_2026 DROP CONSTRAINT IF EXISTS market_time_series_2026_region_id_date_metric_name_data_sou_key;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'market_time_series'::regclass
        AND conname = 'market_time_series_unique'
    ) THEN
        ALTER TABLE market_time_series
        ADD CONSTRAINT market_time_series_unique 
        UNIQUE (region_id, date, metric_name, data_source, attributes);
    END IF;
END $$;

