// Run with: npx tsx scripts/generate-metro-slugs.ts
//
// Fetches all metros from the backend API and generates
// packages/frontend/lib/data/metro-slug-data.ts with static lookup maps.

const API_URL = process.env.API_URL || 'http://localhost:3001';

interface MetroEntry {
  regionId: number;
  name: string;
}

function generateSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[,.'()]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function getShortName(fullName: string): string {
  const commaIndex = fullName.indexOf(',');
  if (commaIndex === -1) return fullName;

  const city = fullName.substring(0, commaIndex).split('-')[0].trim();
  const state = fullName.substring(commaIndex + 1).trim().split('-')[0].trim();
  return `${city}, ${state}`;
}

function getState(fullName: string): string {
  const commaIndex = fullName.indexOf(',');
  if (commaIndex === -1) return '';
  return fullName.substring(commaIndex + 1).trim().split('-')[0].trim();
}

async function main() {
  const endpoint = `${API_URL}/api/markets/metros`;
  console.log(`Fetching metros from ${endpoint}...`);

  const res = await fetch(endpoint);
  if (!res.ok) {
    throw new Error(`API returned ${res.status}: ${await res.text()}`);
  }

  const metros: MetroEntry[] = await res.json();
  console.log(`Fetched ${metros.length} metros.`);

  const entries = metros.map((m) => ({
    cbsaCode: String(m.regionId),
    slug: generateSlug(m.name),
    name: m.name,
    shortName: getShortName(m.name),
    state: getState(m.name),
  }));

  // Check for duplicate slugs
  const slugMap = new Map<string, string>();
  let duplicateCount = 0;
  for (const entry of entries) {
    if (slugMap.has(entry.slug)) {
      console.warn(
        `WARNING: Duplicate slug "${entry.slug}" -- ${entry.name} vs ${slugMap.get(entry.slug)}`,
      );
      duplicateCount++;
    }
    slugMap.set(entry.slug, entry.name);
  }

  if (duplicateCount > 0) {
    console.warn(`\nFound ${duplicateCount} duplicate slug(s). Review the output for conflicts.`);
  }

  const output = `// Auto-generated by scripts/generate-metro-slugs.ts
// Do not edit manually. Re-run the script to update.
// Generated: ${new Date().toISOString()}
// Total metros: ${entries.length}

import type { MetroSlugEntry } from './metro-slugs';

export const METRO_SLUG_DATA: MetroSlugEntry[] = ${JSON.stringify(entries, null, 2)};

/** Map from slug to metro entry for O(1) lookup */
export const SLUG_TO_METRO = new Map<string, MetroSlugEntry>(
  METRO_SLUG_DATA.map(e => [e.slug, e])
);

/** Map from CBSA code to metro entry for O(1) lookup */
export const CBSA_TO_METRO = new Map<string, MetroSlugEntry>(
  METRO_SLUG_DATA.map(e => [e.cbsaCode, e])
);
`;

  const fs = await import('fs');
  const path = await import('path');
  const outPath = path.join('packages', 'frontend', 'lib', 'data', 'metro-slug-data.ts');
  fs.writeFileSync(outPath, output);
  console.log(`\nWritten to ${outPath}`);
  console.log(`Total entries: ${entries.length}`);
  console.log(`Unique slugs: ${slugMap.size}`);
}

main().catch((err) => {
  console.error('Failed:', err.message);
  process.exit(1);
});
