/**
 * Import Economic Data
 *
 * Imports economic data (unemployment, GDP, cost of living) from CSVs
 * generated by economic_data_downloader.py
 *
 * Usage:
 *   # Import all geographies
 *   npx tsx scripts/import-economic-data.ts
 *
 *   # Import specific geography (supports multiple)
 *   npx tsx scripts/import-economic-data.ts --geo=state
 *   npx tsx scripts/import-economic-data.ts --geo=state --geo=metro
 */

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { createImportClient } from './census-economic-import/db-client';
import {
  parseEconomicNationalCSV,
  parseEconomicStateCSV,
  parseEconomicMetroCSV,
  parseEconomicCountyCSV,
  importEconomicNationalRecords,
  importEconomicStateRecords,
  importEconomicMetroRecords,
  importEconomicCountyRecords
} from './census-economic-import/csv-processor';
import type { ImportResult } from './census-economic-import/types';
import { refreshCalculatedMetrics } from './utils/refresh-calculated-metrics';
import { createIngestionLogger, IngestionSource } from './utils/ingestion-logger';
import { logIngestionDetail, EXPECTED_REGIONS } from './utils/log-ingestion-detail';
import { computeWideFormatMetricStats } from './utils/compute-wide-format-metric-stats';

// Metric columns present in all economic geography levels
const ECONOMIC_METRICS_BASE = [
  'unemployment_rate', 'unemployment_rate_yoy',
  'total_nonfarm_employment', 'employment_yoy',
  'gdp_millions', 'real_gdp_millions', 'gdp_yoy',
];

// RPP metrics only available at state and metro levels
const ECONOMIC_METRICS_RPP = [
  'rpp_all_items', 'rpp_goods', 'rpp_housing', 'rpp_utilities', 'rpp_other_services',
];

/** Return the geo ID field name for a given economic geography level */
function getEconomicGeoField(geoId: string): string | null {
  switch (geoId) {
    case 'state': return 'state_fips';
    case 'metro': return 'cbsa_code';
    case 'county': return 'fips_code';
    default: return null; // national
  }
}

// Use process.cwd() for compatibility with both CommonJS and ES modules
const DATA_DIR = join(process.cwd(), 'data/economic');

interface DatasetConfig {
  id: string;
  name: string;
  files: string[];
  parser: (content: string) => any[];
  importer: (supabase: any, records: any[]) => Promise<ImportResult>;
}

const DATASETS: DatasetConfig[] = [
  {
    id: 'national',
    name: 'Economic National',
    files: ['economic_national.csv', 'fred_national.csv'],
    parser: parseEconomicNationalCSV,
    importer: importEconomicNationalRecords
  },
  {
    id: 'state',
    name: 'Economic State',
    files: ['economic_state.csv', 'fred_state.csv'],
    parser: parseEconomicStateCSV,
    importer: importEconomicStateRecords
  },
  {
    id: 'metro',
    name: 'Economic Metro',
    files: ['economic_metro.csv', 'fred_metro.csv'],
    parser: parseEconomicMetroCSV,
    importer: importEconomicMetroRecords
  },
  {
    id: 'county',
    name: 'Economic County',
    files: ['economic_county.csv', 'fred_county.csv'],
    parser: parseEconomicCountyCSV,
    importer: importEconomicCountyRecords
  }
];

function findDataFile(files: string[]): string | null {
  for (const file of files) {
    const path = join(DATA_DIR, file);
    if (existsSync(path)) {
      return path;
    }
  }
  return null;
}

async function importDataset(supabase: any, config: DatasetConfig): Promise<ImportResult | null> {
  const filePath = findDataFile(config.files);

  if (!filePath) {
    console.log(`  Skipping ${config.name}: No data file found`);
    console.log(`    Looked for: ${config.files.join(', ')}`);
    return null;
  }

  console.log(`\nImporting ${config.name}...`);
  console.log(`  Source: ${filePath}`);

  // Determine source based on dataset (national is FRED, others are BLS)
  const source: IngestionSource = config.id === 'national' ? 'fred' : 'bls';

  // Create ingestion logger for this dataset
  const logger = createIngestionLogger(supabase, {
    source,
    tableName: `economic_${config.id}`,
    datasetId: `economic-${config.id}`
  });

  try {
    const csvContent = readFileSync(filePath, 'utf-8');
    const records = config.parser(csvContent);

    console.log(`  Parsed ${records.length} records`);

    if (records.length === 0) {
      console.log(`  No records to import`);
      return null;
    }

    // Start ingestion log and capture run ID for detail logging
    const runId = await logger.start(records.length);
    const importStart = Date.now();

    const result = await config.importer(supabase, records);

    const importDurationMs = Date.now() - importStart;

    // Complete ingestion log
    await logger.complete({
      recordsProcessed: records.length,
      recordsSuccess: result.recordsInserted,
      recordsError: result.errors,
      errors: result.errors > 0 ? [`${result.errors} records failed`] : []
    });

    // Log per-metric details for the admin pipeline details view
    if (runId && result.success) {
      const metricColumns = (config.id === 'state' || config.id === 'metro')
        ? [...ECONOMIC_METRICS_BASE, ...ECONOMIC_METRICS_RPP]
        : ECONOMIC_METRICS_BASE;

      const geoField = getEconomicGeoField(config.id);
      const perMetricStats = computeWideFormatMetricStats(records, metricColumns, 'period_date', geoField);
      const tableName = `economic_${config.id}`;
      const expectedRegions = EXPECTED_REGIONS[config.id] || 0;

      for (const [metricName, stats] of perMetricStats) {
        if (stats.count === 0) continue;

        const coveragePct = expectedRegions
          ? Math.min(100, (stats.regionCount / expectedRegions) * 100)
          : 0;

        await logIngestionDetail(
          supabase, runId, metricName, config.id,
          'success', stats.count, 0, importDurationMs,
          undefined,
          { tableName, latestDataDate: stats.latestDate ?? undefined, coveragePct },
        );
      }

      console.log(`  Logged per-metric details for ${perMetricStats.size} metrics`);
    }

    return result;
  } catch (error: any) {
    console.error(`  Error importing ${config.name}: ${error.message}`);
    await logger.fail(error.message);
    return {
      datasetId: config.id,
      success: false,
      recordsInserted: 0,
      recordsUpdated: 0,
      errors: 1
    };
  }
}

async function main() {
  const startTime = Date.now();
  const args = process.argv.slice(2);

  // Parse --geo arguments (supports multiple: --geo=state --geo=metro)
  const geoFilters: string[] = [];
  let batchSize: number = 1000;

  const noRefresh = args.includes('--no-refresh');

  for (const arg of args) {
    if (arg.startsWith('--geo=')) {
      geoFilters.push(arg.split('=')[1].toLowerCase());
    }
    if (arg.startsWith('--batch=')) {
      const val = parseInt(arg.split('=')[1]);
      if (!isNaN(val)) batchSize = val;
    }
  }

  console.log('Economic Data Import');
  console.log('='.repeat(60));
  console.log(`Date: ${new Date().toISOString()}`);
  console.log(`Data directory: ${DATA_DIR}`);
  console.log(`Batch size: ${batchSize}`);
  if (geoFilters.length > 0) {
    console.log(`Geography filter: ${geoFilters.join(', ')}`);
  }

  // Check if data directory exists
  if (!existsSync(DATA_DIR)) {
    console.error(`\nData directory not found: ${DATA_DIR}`);
    console.error('Please run economic_data_downloader.py first to download the data.');
    process.exit(1);
  }

  // Create database client
  const supabase = createImportClient();

  // Filter datasets if geo(s) specified
  const datasetsToImport = geoFilters.length > 0
    ? DATASETS.filter(d => geoFilters.includes(d.id))
    : DATASETS;

  if (datasetsToImport.length === 0) {
    console.error(`\nUnknown geography: ${geoFilters.join(', ')}`);
    console.error('Valid options: national, state, metro, county');
    process.exit(1);
  }

  // Import each dataset
  const results: ImportResult[] = [];
  for (const config of datasetsToImport) {
    const result = await importDataset(supabase, config);
    if (result) {
      results.push(result);
    }
  }

  // Summary
  const duration = ((Date.now() - startTime) / 1000).toFixed(1);
  const totalRecords = results.reduce((sum, r) => sum + r.recordsInserted, 0);
  const totalErrors = results.reduce((sum, r) => sum + r.errors, 0);

  console.log('\n' + '='.repeat(60));
  console.log('IMPORT SUMMARY');
  console.log('='.repeat(60));

  for (const result of results) {
    const status = result.success ? 'OK' : 'ERRORS';
    console.log(`${result.datasetId}: ${result.recordsInserted} records [${status}]`);
  }

  console.log('-'.repeat(60));
  console.log(`Total records: ${totalRecords}`);
  console.log(`Total errors: ${totalErrors}`);
  console.log(`Duration: ${duration}s`);
  console.log('='.repeat(60));

  if (totalErrors > 0) {
    console.log('\nImport completed with errors');
    process.exit(1);
  }

  // Refresh calculated metrics after successful import
  if (totalRecords > 0 && !noRefresh) {
    await refreshCalculatedMetrics(supabase);
  }

  console.log('\nImport completed successfully');
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
