/**
 * Import Building Permits Data to Supabase
 *
 * Imports building permits data from CSVs generated by download-building-permits.ts
 *
 * Usage:
 *   # Import all geographies
 *   npx tsx scripts/import-building-permits.ts
 *
 *   # Import specific geography (supports multiple)
 *   npx tsx scripts/import-building-permits.ts --geo=county
 *   npx tsx scripts/import-building-permits.ts --geo=county --geo=state
 */

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { createImportClient } from './census-economic-import/db-client';
import { parse } from 'csv-parse/sync';
import { createIngestionLogger } from './utils/ingestion-logger';

const DATA_DIR = join(process.cwd(), 'data/permits');

interface PermitRecord {
  period_date: string;
  fips_code: string;
  county_name: string;
  state_fips: string;
  region_code: string;
  division_code: string;
  sf_buildings: number | null;
  sf_units: number | null;
  sf_value: number | null;
  duplex_buildings: number | null;
  duplex_units: number | null;
  duplex_value: number | null;
  small_multi_buildings: number | null;
  small_multi_units: number | null;
  small_multi_value: number | null;
  large_multi_buildings: number | null;
  large_multi_units: number | null;
  large_multi_value: number | null;
  total_buildings: number | null;
  total_units: number | null;
  total_value: number | null;
  sf_units_yoy: number | null;
  total_units_yoy: number | null;
}

interface ImportResult {
  datasetId: string;
  success: boolean;
  recordsInserted: number;
  recordsUpdated: number;
  errors: number;
}

function parseNumeric(value: string | undefined): number | null {
  if (!value || value.trim() === '') return null;
  const num = parseFloat(value);
  return isNaN(num) ? null : num;
}

function parseInteger(value: string | undefined): number | null {
  if (!value || value.trim() === '') return null;
  const num = parseInt(value, 10);
  return isNaN(num) ? null : num;
}

function parsePermitsCSV(csvContent: string): PermitRecord[] {
  const records = parse(csvContent, {
    columns: true,
    skip_empty_lines: true,
    trim: true
  });

  // Deduplicate by period_date + fips_code (keep last occurrence)
  const seen = new Map<string, any>();
  for (const row of records) {
    const key = `${row.period_date}|${row.fips_code}`;
    seen.set(key, row);
  }

  return Array.from(seen.values()).map((row: any) => ({
    period_date: row.period_date,
    fips_code: row.fips_code,
    county_name: row.county_name || null,
    state_fips: row.state_fips,
    region_code: row.region_code || null,
    division_code: row.division_code || null,
    sf_buildings: parseInteger(row.sf_buildings),
    sf_units: parseInteger(row.sf_units),
    sf_value: parseInteger(row.sf_value),
    duplex_buildings: parseInteger(row.duplex_buildings),
    duplex_units: parseInteger(row.duplex_units),
    duplex_value: parseInteger(row.duplex_value),
    small_multi_buildings: parseInteger(row.small_multi_buildings),
    small_multi_units: parseInteger(row.small_multi_units),
    small_multi_value: parseInteger(row.small_multi_value),
    large_multi_buildings: parseInteger(row.large_multi_buildings),
    large_multi_units: parseInteger(row.large_multi_units),
    large_multi_value: parseInteger(row.large_multi_value),
    total_buildings: parseInteger(row.total_buildings),
    total_units: parseInteger(row.total_units),
    total_value: parseInteger(row.total_value),
    sf_units_yoy: parseNumeric(row.sf_units_yoy),
    total_units_yoy: parseNumeric(row.total_units_yoy)
  }));
}

async function importCountyPermits(supabase: any, records: PermitRecord[]): Promise<ImportResult> {
  const tableName = 'permits_county';
  let inserted = 0;
  let updated = 0;
  let errors = 0;

  // Process in batches of 500
  const batchSize = 500;
  const batches = [];
  for (let i = 0; i < records.length; i += batchSize) {
    batches.push(records.slice(i, i + batchSize));
  }

  console.log(`  Processing ${batches.length} batches of ${batchSize} records...`);

  for (let i = 0; i < batches.length; i++) {
    const batch = batches[i];

    const { data, error } = await supabase
      .from(tableName)
      .upsert(
        batch.map(r => ({
          period_date: r.period_date,
          fips_code: r.fips_code,
          county_name: r.county_name,
          state_fips: r.state_fips,
          region_code: r.region_code,
          division_code: r.division_code,
          sf_buildings: r.sf_buildings,
          sf_units: r.sf_units,
          sf_value: r.sf_value,
          duplex_buildings: r.duplex_buildings,
          duplex_units: r.duplex_units,
          duplex_value: r.duplex_value,
          small_multi_buildings: r.small_multi_buildings,
          small_multi_units: r.small_multi_units,
          small_multi_value: r.small_multi_value,
          large_multi_buildings: r.large_multi_buildings,
          large_multi_units: r.large_multi_units,
          large_multi_value: r.large_multi_value,
          total_buildings: r.total_buildings,
          total_units: r.total_units,
          total_value: r.total_value,
          sf_units_yoy: r.sf_units_yoy,
          total_units_yoy: r.total_units_yoy,
          updated_at: new Date().toISOString()
        })),
        { onConflict: 'period_date,fips_code' }
      );

    if (error) {
      console.error(`  Batch ${i + 1} error: ${error.message}`);
      errors += batch.length;
    } else {
      inserted += batch.length;
    }

    // Progress indicator
    if ((i + 1) % 10 === 0 || i === batches.length - 1) {
      process.stdout.write(`\r  Progress: ${i + 1}/${batches.length} batches`);
    }
  }

  console.log(''); // New line after progress

  return {
    datasetId: 'permits_county',
    success: errors === 0,
    recordsInserted: inserted,
    recordsUpdated: updated,
    errors
  };
}

async function importStatePermits(supabase: any, records: PermitRecord[]): Promise<ImportResult> {
  const tableName = 'permits_state';
  let inserted = 0;
  let updated = 0;
  let errors = 0;

  // Process in batches of 500
  const batchSize = 500;
  const batches = [];
  for (let i = 0; i < records.length; i += batchSize) {
    batches.push(records.slice(i, i + batchSize));
  }

  console.log(`  Processing ${batches.length} batches of ${batchSize} records...`);

  for (let i = 0; i < batches.length; i++) {
    const batch = batches[i];

    const { data, error } = await supabase
      .from(tableName)
      .upsert(
        batch.map(r => ({
          period_date: r.period_date,
          state_fips: r.state_fips,
          state_name: null, // Could be added later with lookup
          sf_buildings: r.sf_buildings,
          sf_units: r.sf_units,
          sf_value: r.sf_value,
          duplex_buildings: r.duplex_buildings,
          duplex_units: r.duplex_units,
          duplex_value: r.duplex_value,
          small_multi_buildings: r.small_multi_buildings,
          small_multi_units: r.small_multi_units,
          small_multi_value: r.small_multi_value,
          large_multi_buildings: r.large_multi_buildings,
          large_multi_units: r.large_multi_units,
          large_multi_value: r.large_multi_value,
          total_buildings: r.total_buildings,
          total_units: r.total_units,
          total_value: r.total_value,
          sf_units_yoy: r.sf_units_yoy,
          total_units_yoy: r.total_units_yoy,
          updated_at: new Date().toISOString()
        })),
        { onConflict: 'period_date,state_fips' }
      );

    if (error) {
      console.error(`  Batch ${i + 1} error: ${error.message}`);
      errors += batch.length;
    } else {
      inserted += batch.length;
    }

    // Progress indicator
    if ((i + 1) % 10 === 0 || i === batches.length - 1) {
      process.stdout.write(`\r  Progress: ${i + 1}/${batches.length} batches`);
    }
  }

  console.log(''); // New line after progress

  return {
    datasetId: 'permits_state',
    success: errors === 0,
    recordsInserted: inserted,
    recordsUpdated: updated,
    errors
  };
}

interface DatasetConfig {
  id: string;
  name: string;
  file: string;
  importer: (supabase: any, records: PermitRecord[]) => Promise<ImportResult>;
}

const DATASETS: DatasetConfig[] = [
  {
    id: 'county',
    name: 'Permits County',
    file: 'permits_county.csv',
    importer: importCountyPermits
  },
  {
    id: 'state',
    name: 'Permits State',
    file: 'permits_state.csv',
    importer: importStatePermits
  }
];

async function main() {
  const startTime = Date.now();
  const args = process.argv.slice(2);

  // Parse --geo arguments (supports multiple: --geo=county --geo=state)
  const geoFilters: string[] = [];
  for (const arg of args) {
    if (arg.startsWith('--geo=')) {
      geoFilters.push(arg.split('=')[1].toLowerCase());
    }
  }

  console.log('Building Permits Data Import');
  console.log('='.repeat(60));
  console.log(`Date: ${new Date().toISOString()}`);
  console.log(`Data directory: ${DATA_DIR}`);
  if (geoFilters.length > 0) {
    console.log(`Geography filter: ${geoFilters.join(', ')}`);
  }

  // Check if data directory exists
  if (!existsSync(DATA_DIR)) {
    console.error(`\nData directory not found: ${DATA_DIR}`);
    console.error('Please run download-building-permits.ts first to download the data.');
    process.exit(1);
  }

  // Create database client
  const supabase = createImportClient();

  const results: ImportResult[] = [];

  // Import each dataset
  for (const config of DATASETS) {
    // Skip if geography filter doesn't match
    if (geoFilters.length > 0 && !geoFilters.includes(config.id)) {
      continue;
    }

    const filePath = join(DATA_DIR, config.file);

    if (!existsSync(filePath)) {
      console.log(`\nSkipping ${config.name}: ${config.file} not found`);
      continue;
    }

    console.log(`\nImporting ${config.name}...`);
    console.log(`  Source: ${filePath}`);

    // Create ingestion logger for this dataset
    const logger = createIngestionLogger(supabase, {
      source: 'permits',
      tableName: `permits_${config.id}`,
      datasetId: `permits-${config.id}`
    });

    try {
      const csvContent = readFileSync(filePath, 'utf-8');
      const records = parsePermitsCSV(csvContent);

      console.log(`  Parsed ${records.length} records`);

      if (records.length === 0) {
        console.log(`  No records to import`);
        continue;
      }

      // Show date range
      const dates = records.map(r => r.period_date).sort();
      console.log(`  Date range: ${dates[0]} to ${dates[dates.length - 1]}`);

      // Start ingestion log
      await logger.start(records.length);

      const result = await config.importer(supabase, records);
      results.push(result);

      // Complete ingestion log
      await logger.complete({
        recordsProcessed: records.length,
        recordsSuccess: result.recordsInserted,
        recordsError: result.errors,
        errors: result.errors > 0 ? [`${result.errors} records failed`] : []
      });

      console.log(`  Imported: ${result.recordsInserted} records`);
      if (result.errors > 0) {
        console.log(`  Errors: ${result.errors}`);
      }
    } catch (error: any) {
      console.error(`  Error importing ${config.name}: ${error.message}`);
      await logger.fail(error.message);
      results.push({
        datasetId: config.id,
        success: false,
        recordsInserted: 0,
        recordsUpdated: 0,
        errors: 1
      });
    }
  }

  // Summary
  const duration = ((Date.now() - startTime) / 1000).toFixed(1);
  const totalRecords = results.reduce((sum, r) => sum + r.recordsInserted, 0);
  const totalErrors = results.reduce((sum, r) => sum + r.errors, 0);

  console.log(`\n${'='.repeat(60)}`);
  console.log('Import Summary');
  console.log('='.repeat(60));
  console.log(`Total records imported: ${totalRecords}`);
  console.log(`Total errors: ${totalErrors}`);
  console.log(`Duration: ${duration}s`);

  if (totalErrors > 0) {
    console.log('\nCompleted with errors');
    process.exit(1);
  } else {
    console.log('\nImport completed successfully!');
  }
}

main().catch(error => {
  console.error('Error:', error);
  process.exit(1);
});
