/**
 * Import Census Data
 *
 * Imports Census ACS and CBP data from CSVs generated by economic_data_downloader.py
 *
 * Usage:
 *   # Import all geographies
 *   npx tsx scripts/import-census-data.ts
 *
 *   # Import specific geography
 *   npx tsx scripts/import-census-data.ts --geo=state
 *   npx tsx scripts/import-census-data.ts --geo=metro
 *   npx tsx scripts/import-census-data.ts --geo=county
 */

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { createImportClient } from './census-economic-import/db-client';
import {
  parseCensusNationalCSV,
  parseCensusStateCSV,
  parseCensusMetroCSV,
  parseCensusCountyCSV,
  parseCensusCityCSV,
  parseCensusZipCSV,
  importCensusNationalRecords,
  importCensusStateRecords,
  importCensusMetroRecords,
  importCensusCountyRecords,
  importCensusCityRecords,
  importCensusZipRecords
} from './census-economic-import/csv-processor';
import type { ImportResult } from './census-economic-import/types';
import { refreshCalculatedMetrics } from './utils/refresh-calculated-metrics';
import { createIngestionLogger } from './utils/ingestion-logger';
import { logIngestionDetail, EXPECTED_REGIONS } from './utils/log-ingestion-detail';
import { computeWideFormatMetricStats } from './utils/compute-wide-format-metric-stats';

// Core ACS demographic/housing metrics (all geography levels)
const CENSUS_METRICS_BASE = [
  'total_population', 'population_yoy', 'median_age',
  'median_household_income', 'income_yoy', 'per_capita_income',
  'total_housing_units', 'owner_occupied_units', 'renter_occupied_units',
  'homeownership_rate', 'median_home_value', 'median_gross_rent',
  'rent_as_pct_of_income',
];

// County Business Patterns metrics (national, state, county, zip)
const CENSUS_METRICS_CBP = [
  'total_employment', 'total_establishments', 'annual_payroll',
];

/** Return the geo ID field name for a given census geography level */
function getCensusGeoField(geoId: string): string | null {
  switch (geoId) {
    case 'state': return 'state_fips';
    case 'metro': return 'cbsa_code';
    case 'county': return 'fips_code';
    case 'city': return 'place_fips';
    case 'zip': return 'zcta';
    default: return null; // national
  }
}

/** Return which metric columns apply for a given census geography level */
function getCensusMetricColumns(geoId: string): string[] {
  // CBP metrics are available for national, state, county, zip — NOT metro or city
  if (geoId === 'metro' || geoId === 'city') {
    return CENSUS_METRICS_BASE;
  }
  return [...CENSUS_METRICS_BASE, ...CENSUS_METRICS_CBP];
}

// Use process.cwd() for compatibility with both CommonJS and ES modules
const DATA_DIR = join(process.cwd(), 'data/economic');

interface DatasetConfig {
  id: string;
  name: string;
  files: string[];
  parser: (content: string) => any[];
  importer: (supabase: any, records: any[]) => Promise<ImportResult>;
}

const DATASETS: DatasetConfig[] = [
  {
    id: 'national',
    name: 'Census National',
    files: ['acs_national.csv', 'census_national.csv'],
    parser: parseCensusNationalCSV,
    importer: importCensusNationalRecords
  },
  {
    id: 'state',
    name: 'Census State',
    files: ['acs_state.csv', 'census_state.csv'],
    parser: parseCensusStateCSV,
    importer: importCensusStateRecords
  },
  {
    id: 'metro',
    name: 'Census Metro',
    files: ['acs_metro.csv', 'census_metro.csv'],
    parser: parseCensusMetroCSV,
    importer: importCensusMetroRecords
  },
  {
    id: 'county',
    name: 'Census County',
    files: ['acs_county.csv', 'census_county.csv'],
    parser: parseCensusCountyCSV,
    importer: importCensusCountyRecords
  },
  {
    id: 'city',
    name: 'Census City',
    files: ['acs_place.csv', 'acs_city.csv', 'census_city.csv'],
    parser: parseCensusCityCSV,
    importer: importCensusCityRecords
  },
  {
    id: 'zip',
    name: 'Census ZIP',
    files: ['acs_zcta.csv', 'acs_zip.csv', 'census_zip.csv'],
    parser: parseCensusZipCSV,
    importer: importCensusZipRecords
  }
];

function findDataFile(files: string[]): string | null {
  for (const file of files) {
    const path = join(DATA_DIR, file);
    if (existsSync(path)) {
      return path;
    }
  }
  return null;
}

async function importDataset(supabase: any, config: DatasetConfig): Promise<ImportResult | null> {
  const filePath = findDataFile(config.files);

  if (!filePath) {
    console.log(`  Skipping ${config.name}: No data file found`);
    console.log(`    Looked for: ${config.files.join(', ')}`);
    return null;
  }

  console.log(`\nImporting ${config.name}...`);
  console.log(`  Source: ${filePath}`);

  // Create ingestion logger for this dataset
  const logger = createIngestionLogger(supabase, {
    source: 'census',
    tableName: `census_${config.id}`,
    datasetId: `census-${config.id}`
  });

  try {
    const csvContent = readFileSync(filePath, 'utf-8');
    const records = config.parser(csvContent);

    console.log(`  Parsed ${records.length} records`);

    if (records.length === 0) {
      console.log(`  No records to import`);
      return null;
    }

    // Start ingestion log and capture run ID for detail logging
    const runId = await logger.start(records.length);
    const importStart = Date.now();

    const result = await config.importer(supabase, records);

    const importDurationMs = Date.now() - importStart;

    // Complete ingestion log
    await logger.complete({
      recordsProcessed: records.length,
      recordsSuccess: result.recordsInserted,
      recordsError: result.errors,
      errors: result.errors > 0 ? [`${result.errors} records failed`] : []
    });

    // Log per-metric details for the admin pipeline details view
    if (runId && result.success) {
      const metricColumns = getCensusMetricColumns(config.id);
      const geoField = getCensusGeoField(config.id);
      const perMetricStats = computeWideFormatMetricStats(records, metricColumns, 'year', geoField);
      const tableName = `census_${config.id}`;
      const expectedRegions = EXPECTED_REGIONS[config.id] || 0;

      for (const [metricName, stats] of perMetricStats) {
        if (stats.count === 0) continue;

        const coveragePct = expectedRegions
          ? Math.min(100, (stats.regionCount / expectedRegions) * 100)
          : 0;

        await logIngestionDetail(
          supabase, runId, metricName, config.id,
          'success', stats.count, 0, importDurationMs,
          undefined,
          { tableName, latestDataDate: stats.latestDate ?? undefined, coveragePct },
        );
      }

      console.log(`  Logged per-metric details for ${perMetricStats.size} metrics`);
    }

    return result;
  } catch (error: any) {
    console.error(`  Error importing ${config.name}: ${error.message}`);
    await logger.fail(error.message);
    return {
      datasetId: config.id,
      success: false,
      recordsInserted: 0,
      recordsUpdated: 0,
      errors: 1
    };
  }
}

async function main() {
  const startTime = Date.now();
  const args = process.argv.slice(2);

  // Parse --geo argument
  let geoFilter: string | null = null;
  for (const arg of args) {
    if (arg.startsWith('--geo=')) {
      geoFilter = arg.split('=')[1].toLowerCase();
    }
  }

  console.log('Census Data Import');
  console.log('='.repeat(60));
  console.log(`Date: ${new Date().toISOString()}`);
  console.log(`Data directory: ${DATA_DIR}`);
  if (geoFilter) {
    console.log(`Geography filter: ${geoFilter}`);
  }

  // Check if data directory exists
  if (!existsSync(DATA_DIR)) {
    console.error(`\nData directory not found: ${DATA_DIR}`);
    console.error('Please run economic_data_downloader.py first to download the data.');
    process.exit(1);
  }

  // Create database client
  const supabase = createImportClient();

  // Filter datasets if geo specified
  const datasetsToImport = geoFilter
    ? DATASETS.filter(d => d.id === geoFilter)
    : DATASETS;

  if (datasetsToImport.length === 0) {
    console.error(`\nUnknown geography: ${geoFilter}`);
    console.error('Valid options: national, state, metro, county, city, zip');
    process.exit(1);
  }

  // Import each dataset
  const results: ImportResult[] = [];
  for (const config of datasetsToImport) {
    const result = await importDataset(supabase, config);
    if (result) {
      results.push(result);
    }
  }

  // Summary
  const duration = ((Date.now() - startTime) / 1000).toFixed(1);
  const totalRecords = results.reduce((sum, r) => sum + r.recordsInserted, 0);
  const totalErrors = results.reduce((sum, r) => sum + r.errors, 0);

  console.log('\n' + '='.repeat(60));
  console.log('IMPORT SUMMARY');
  console.log('='.repeat(60));

  for (const result of results) {
    const status = result.success ? 'OK' : 'ERRORS';
    console.log(`${result.datasetId}: ${result.recordsInserted} records [${status}]`);
  }

  console.log('-'.repeat(60));
  console.log(`Total records: ${totalRecords}`);
  console.log(`Total errors: ${totalErrors}`);
  console.log(`Duration: ${duration}s`);
  console.log('='.repeat(60));

  if (totalErrors > 0) {
    console.log('\nImport completed with errors');
    process.exit(1);
  }

  // Refresh calculated metrics after successful import
  if (totalRecords > 0) {
    await refreshCalculatedMetrics(supabase);
  }

  console.log('\nImport completed successfully');
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
