/**
 * Import Economic Data
 *
 * Imports economic data (unemployment, GDP, cost of living) from CSVs
 * generated by economic_data_downloader.py
 *
 * Usage:
 *   # Import all geographies
 *   npx tsx scripts/import-economic-data.ts
 *
 *   # Import specific geography
 *   npx tsx scripts/import-economic-data.ts --geo=state
 *   npx tsx scripts/import-economic-data.ts --geo=metro
 *   npx tsx scripts/import-economic-data.ts --geo=county
 */

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { createImportClient } from './census-economic-import/db-client';
import {
  parseEconomicNationalCSV,
  parseEconomicStateCSV,
  parseEconomicMetroCSV,
  parseEconomicCountyCSV,
  importEconomicNationalRecords,
  importEconomicStateRecords,
  importEconomicMetroRecords,
  importEconomicCountyRecords
} from './census-economic-import/csv-processor';
import type { ImportResult } from './census-economic-import/types';
import { refreshCalculatedMetrics } from './utils/refresh-calculated-metrics';

const DATA_DIR = join(__dirname, '../data/economic');

interface DatasetConfig {
  id: string;
  name: string;
  files: string[];
  parser: (content: string) => any[];
  importer: (supabase: any, records: any[]) => Promise<ImportResult>;
}

const DATASETS: DatasetConfig[] = [
  {
    id: 'national',
    name: 'Economic National',
    files: ['economic_national.csv', 'fred_national.csv'],
    parser: parseEconomicNationalCSV,
    importer: importEconomicNationalRecords
  },
  {
    id: 'state',
    name: 'Economic State',
    files: ['economic_state.csv', 'fred_state.csv'],
    parser: parseEconomicStateCSV,
    importer: importEconomicStateRecords
  },
  {
    id: 'metro',
    name: 'Economic Metro',
    files: ['economic_metro.csv', 'fred_metro.csv'],
    parser: parseEconomicMetroCSV,
    importer: importEconomicMetroRecords
  },
  {
    id: 'county',
    name: 'Economic County',
    files: ['economic_county.csv', 'fred_county.csv'],
    parser: parseEconomicCountyCSV,
    importer: importEconomicCountyRecords
  }
];

function findDataFile(files: string[]): string | null {
  for (const file of files) {
    const path = join(DATA_DIR, file);
    if (existsSync(path)) {
      return path;
    }
  }
  return null;
}

async function importDataset(supabase: any, config: DatasetConfig): Promise<ImportResult | null> {
  const filePath = findDataFile(config.files);

  if (!filePath) {
    console.log(`  Skipping ${config.name}: No data file found`);
    console.log(`    Looked for: ${config.files.join(', ')}`);
    return null;
  }

  console.log(`\nImporting ${config.name}...`);
  console.log(`  Source: ${filePath}`);

  try {
    const csvContent = readFileSync(filePath, 'utf-8');
    const records = config.parser(csvContent);

    console.log(`  Parsed ${records.length} records`);

    if (records.length === 0) {
      console.log(`  No records to import`);
      return null;
    }

    const result = await config.importer(supabase, records);
    return result;
  } catch (error: any) {
    console.error(`  Error importing ${config.name}: ${error.message}`);
    return {
      datasetId: config.id,
      success: false,
      recordsInserted: 0,
      recordsUpdated: 0,
      errors: 1
    };
  }
}

async function main() {
  const startTime = Date.now();
  const args = process.argv.slice(2);

  // Parse --geo argument
  let geoFilter: string | null = null;
  for (const arg of args) {
    if (arg.startsWith('--geo=')) {
      geoFilter = arg.split('=')[1].toLowerCase();
    }
  }

  console.log('Economic Data Import');
  console.log('='.repeat(60));
  console.log(`Date: ${new Date().toISOString()}`);
  console.log(`Data directory: ${DATA_DIR}`);
  if (geoFilter) {
    console.log(`Geography filter: ${geoFilter}`);
  }

  // Check if data directory exists
  if (!existsSync(DATA_DIR)) {
    console.error(`\nData directory not found: ${DATA_DIR}`);
    console.error('Please run economic_data_downloader.py first to download the data.');
    process.exit(1);
  }

  // Create database client
  const supabase = createImportClient();

  // Filter datasets if geo specified
  const datasetsToImport = geoFilter
    ? DATASETS.filter(d => d.id === geoFilter)
    : DATASETS;

  if (datasetsToImport.length === 0) {
    console.error(`\nUnknown geography: ${geoFilter}`);
    console.error('Valid options: national, state, metro, county');
    process.exit(1);
  }

  // Import each dataset
  const results: ImportResult[] = [];
  for (const config of datasetsToImport) {
    const result = await importDataset(supabase, config);
    if (result) {
      results.push(result);
    }
  }

  // Summary
  const duration = ((Date.now() - startTime) / 1000).toFixed(1);
  const totalRecords = results.reduce((sum, r) => sum + r.recordsInserted, 0);
  const totalErrors = results.reduce((sum, r) => sum + r.errors, 0);

  console.log('\n' + '='.repeat(60));
  console.log('IMPORT SUMMARY');
  console.log('='.repeat(60));

  for (const result of results) {
    const status = result.success ? 'OK' : 'ERRORS';
    console.log(`${result.datasetId}: ${result.recordsInserted} records [${status}]`);
  }

  console.log('-'.repeat(60));
  console.log(`Total records: ${totalRecords}`);
  console.log(`Total errors: ${totalErrors}`);
  console.log(`Duration: ${duration}s`);
  console.log('='.repeat(60));

  if (totalErrors > 0) {
    console.log('\nImport completed with errors');
    process.exit(1);
  }

  // Refresh calculated metrics after successful import
  if (totalRecords > 0) {
    await refreshCalculatedMetrics(supabase);
  }

  console.log('\nImport completed successfully');
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
