'use client';

import React from 'react';
import { FileText } from 'lucide-react';

interface PDFLayoutProps {
  title: string;
  subtitle?: string;
  marketName: string;
  score?: number | null;
  scoreLabel?: string;
  grade?: string | null;
  generatedDate: string;
  dataAsOfDate: string;
  aiModel?: string | null;
  sections: Array<{ id: string; name: string }>;
}

export function PDFCoverPage({
  title,
  subtitle,
  marketName,
  score,
  scoreLabel,
  grade,
  generatedDate,
  dataAsOfDate,
  aiModel,
}: Omit<PDFLayoutProps, 'sections'>): React.ReactElement {
  return (
    <div className="report-print-only report-print-cover">
      {/* Logo */}
      <div style={{ marginBottom: '48pt' }}>
        <div style={{
          width: '64px',
          height: '64px',
          borderRadius: '16px',
          backgroundColor: 'var(--report-navy)',
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}>
          <FileText style={{ width: '32px', height: '32px', color: 'white' }} />
        </div>
      </div>

      {/* Title */}
      <h1 style={{
        fontSize: '28pt',
        fontWeight: 600,
        color: 'var(--report-navy)',
        fontFamily: 'var(--report-font-display)',
        marginBottom: '8pt',
        letterSpacing: '-0.02em',
      }}>
        {title}
      </h1>

      {subtitle && (
        <p style={{
          fontSize: '14pt',
          color: 'var(--report-stone)',
          marginBottom: '24pt',
        }}>
          {subtitle}
        </p>
      )}

      {/* Market */}
      <p style={{
        fontSize: '16pt',
        color: 'var(--report-navy)',
        fontWeight: 500,
        marginBottom: '32pt',
      }}>
        {marketName}
      </p>

      {/* Score */}
      {score !== null && score !== undefined && (
        <div style={{
          padding: '16pt 32pt',
          borderRadius: '16px',
          border: '2px solid rgba(27, 46, 74, 0.1)',
          marginBottom: '32pt',
          display: 'inline-block',
        }}>
          <p style={{
            fontSize: '48pt',
            fontWeight: 700,
            color: 'var(--report-navy)',
            fontFamily: 'var(--report-font-display)',
            lineHeight: 1,
          }}>
            {score}
          </p>
          {grade && (
            <p style={{
              fontSize: '18pt',
              fontWeight: 600,
              color: 'var(--report-stone)',
              marginTop: '4pt',
            }}>
              Grade: {grade}
            </p>
          )}
          {scoreLabel && (
            <p style={{
              fontSize: '10pt',
              color: 'var(--report-stone-light)',
              marginTop: '4pt',
              textTransform: 'uppercase',
              letterSpacing: '0.08em',
            }}>
              {scoreLabel}
            </p>
          )}
        </div>
      )}

      {/* Meta */}
      <div style={{
        fontSize: '10pt',
        color: 'var(--report-stone-light)',
        marginTop: 'auto',
        paddingTop: '48pt',
      }}>
        <p>Generated on {generatedDate}</p>
        <p>Data as of {dataAsOfDate}</p>
        {aiModel && <p>AI-Enhanced Analysis</p>}
        <p style={{ marginTop: '16pt', fontWeight: 500 }}>PropertyIQ</p>
      </div>
    </div>
  );
}

export function PDFTableOfContents({
  sections,
}: Pick<PDFLayoutProps, 'sections'>): React.ReactElement {
  return (
    <div className="report-print-only report-print-toc" style={{ padding: '48pt 0' }}>
      <h2 style={{
        fontSize: '20pt',
        fontWeight: 600,
        color: 'var(--report-navy)',
        fontFamily: 'var(--report-font-display)',
        marginBottom: '24pt',
      }}>
        Table of Contents
      </h2>
      <div style={{ maxWidth: '400pt' }}>
        {sections.map((section, index) => (
          <div
            key={section.id}
            style={{
              display: 'flex',
              alignItems: 'baseline',
              justifyContent: 'space-between',
              padding: '6pt 0',
              borderBottom: '0.5pt dotted #d1d5db',
            }}
          >
            <span style={{
              fontSize: '11pt',
              color: 'var(--report-navy)',
            }}>
              {section.name}
            </span>
            <span style={{
              fontSize: '10pt',
              color: 'var(--report-stone-light)',
              marginLeft: '16pt',
            }}>
              {index + 1}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

export function PDFPrintFooter(): React.ReactElement {
  return (
    <div className="report-print-only report-print-footer">
      Generated by PropertyIQ · AI-powered real estate market intelligence
    </div>
  );
}
