import type { StateSlugEntry } from "@/lib/data/state-slug-data";

/**
 * State-specific economic and housing market context paragraphs.
 * Targeting: "[State] real estate market analysis", "best cities to invest in [State]"
 */
const STATE_ECONOMIC_CONTEXT: Record<string, string> = {
  AL: "Alabama's housing market offers some of the Southeast's most accessible entry points, with median home prices well below the national average. The state's economy is diversifying through automotive manufacturing (Mercedes-Benz, Honda, Hyundai), aerospace (Huntsville's NASA and defense corridor), and a growing logistics sector. Markets like Huntsville, Birmingham, and Mobile present distinct investment profiles — from tech-driven appreciation to port-adjacent industrial demand.",
  AK: "Alaska's housing market is uniquely shaped by its resource extraction economy, federal employment, and geographic isolation. Anchorage anchors roughly half the state's population and offers the most liquid real estate market. Oil price cycles historically drive affordability windows. Remote work trends have increased demand from lower-48 buyers, though extreme seasonal dynamics and infrastructure costs are critical factors PropertyIQ accounts for in its scoring models.",
  AZ: "Arizona ranks among the top US states for domestic in-migration, drawing Californians, remote workers, and retirees attracted by warm climate, no state income tax on Social Security, and relative affordability. Metro Phoenix has become a major corporate relocation destination (TSMC, Intel, Toyota) while Tucson benefits from University of Arizona stability. The state's boom-bust history makes PropertyIQ's predictive scoring particularly valuable for timing entry points.",
  AR: "Arkansas combines genuine affordability with improving economic fundamentals. The Fayetteville-Springdale-Rogers metro (home to Walmart headquarters and its supplier ecosystem) has transformed into one of the South's faster-growing markets. Little Rock's state government and healthcare employment provide stability, while emerging remote-work demand is repricing small-town Arkansas markets that were long overlooked.",
  CA: "California's housing market is defined by the nation's most severe supply-demand imbalance, driven by CEQA regulations, geographic constraints, and decades of underbuilding. Despite the highest home prices in the continental US, strong wage growth in technology, entertainment, and biotech sustains demand. PropertyIQ tracks the emerging divergence between coastal metros losing population and inland markets (Riverside, Fresno, Sacramento) absorbing displaced buyers.",
  CO: "Colorado's housing market has absorbed massive remote-work migration from coastal metros, pushing Denver and its suburbs into the top-quartile of appreciation nationally. Boulder's technology ecosystem, Colorado Springs' military and aerospace base, and Fort Collins' university economy each create distinct market dynamics. Mountain communities face acute supply constraints and short-term rental competition that pressure long-term rental yields.",
  CT: "Connecticut's proximity to New York City and Boston, combined with relatively lower prices, has made it a prime beneficiary of pandemic-era suburban migration. Fairfield County's hedge fund wealth drives premium pricing, while Hartford's insurance sector provides stability. Connecticut's property tax burden is among the highest in the nation — a critical variable PropertyIQ factors into its net return projections for investors.",
  DE: "Delaware's zero sales tax, favorable corporate law environment, and proximity to Philadelphia and Washington DC create consistent housing demand in a small market. New Castle County captures most of the activity, with Wilmington's financial sector driving professional demand. The state's low inventory and high homeownership rates create a structurally supply-constrained market with steady appreciation.",
  DC: "The Washington DC metro market is anchored by federal government employment — providing recession resilience unmatched by any private-sector economy. Northern Virginia's technology corridor (Amazon HQ2, Booz Allen, Leidos) has driven some of the region's strongest appreciation. PropertyIQ tracks the diverging performance between urban DC neighborhoods adjusting to post-pandemic office patterns and suburban markets benefiting from remote-work permanence.",
  FL: "Florida's housing market is propelled by zero state income tax, year-round climate, and one of the nation's largest retirement populations. South Florida, Tampa Bay, and the I-4 corridor each operate as distinct economic submarkets. PropertyIQ specifically models Florida's insurance market disruptions — rising premiums from hurricane risk are meaningfully compressing net yields in coastal markets and shifting investor demand toward interior markets.",
  GA: "Georgia's housing market is anchored by metro Atlanta's emergence as a corporate relocation hub (Mercedes-Benz USA, Porsche, NCR, Trilith Studios) and logistics gateway. The Savannah port expansion is driving industrial growth and ancillary housing demand along the I-16 corridor. Georgia's film production incentives have made counties surrounding Atlanta among the fastest-appreciating small markets in the Southeast.",
  HI: "Hawaii's housing market operates under the most extreme supply constraints in the United States — limited buildable land on each island combined with strong demand from mainland buyers, military families, and vacation home investors. Oahu anchors the most liquid market while Maui commands the highest price points. PropertyIQ's scoring for Hawaii accounts for the unique insurance, HOA, and association fee structures that substantially affect net investor returns.",
  ID: "Idaho became one of the nation's top appreciation markets during the pandemic as California and Washington buyers discovered its relative affordability and outdoor lifestyle. Boise transformed from a regional market to a nationally recognized tech hub, while smaller markets like Coeur d'Alene saw speculative demand. PropertyIQ tracks whether Idaho markets are experiencing sustainable demand from employed residents or speculative buyers whose exit could create price corrections.",
  IL: "Illinois housing offers the Midwest's sharpest value proposition, with Chicago metro prices well below comparable coastal cities despite access to world-class amenities, corporate headquarters (Boeing, Caterpillar, Deere), and cultural infrastructure. Property tax rates are the state's most significant investor risk factor — PropertyIQ explicitly incorporates effective tax rates into its InvestorEdge scoring for all Illinois markets.",
  IN: "Indiana's housing market combines genuine affordability with a diversifying economy anchored by manufacturing (auto, life sciences, logistics) and growing university towns. Indianapolis has emerged as a Midwestern tech hub, while Carmel consistently ranks among national quality-of-life leaders. Indiana's low property taxes relative to neighbors make it particularly attractive for buy-and-hold investors analyzing net cash flow.",
  IA: "Iowa's housing market offers exceptional affordability with strong agricultural and insurance-sector economic underpinning. Des Moines has built a significant financial services cluster (Principal, EMC Insurance, Wellmark) that drives professional housing demand in the metro. Iowa City's University of Iowa provides rental stability, while Cedar Rapids offers value-play opportunities for investors targeting Midwest cash flow.",
  KS: "Kansas City straddles the Kansas-Missouri border, creating a single market with two states' tax structures. Wichita's aviation manufacturing (Spirit AeroSystems, Cessna, Beechcraft) anchors the state's second-largest metro with distinct cyclical dynamics. Kansas offers consistently strong rental yields relative to purchase prices — among the highest cap rates available in any US metro market tracked by PropertyIQ.",
  KY: "Kentucky's housing market centers on Louisville's healthcare, spirits industry, and UPS hub employment alongside Lexington's horse industry and University of Kentucky anchor. The state's affordable housing stock, combined with improving downtown revitalization in both metros, creates compelling value-add opportunities for investors. Kentucky's competitive property tax environment enhances net cash flow projections across most markets.",
  LA: "Louisiana's housing market is shaped by its unique cultural geography — New Orleans remains a globally recognized destination market with distinct tourist economy dynamics, while Baton Rouge's petrochemical and state government employment drives more traditional residential demand. PropertyIQ specifically models Louisiana's flood insurance requirements and climate risk factors, which materially affect affordability and net investor returns in coastal parishes.",
  ME: "Maine's housing market has been transformed by remote work, with Boston-area workers discovering Portland and coastal communities as accessible alternatives at substantially lower prices. Inventory across the state remains historically tight, driving appreciation that rivals coastal markets. Maine's strong seasonal rental economy creates split-use investment opportunities — PropertyIQ tracks both long-term rental yield and short-term rental potential in applicable markets.",
  MD: "Maryland's housing market benefits from federal government proximity, with Fort Meade's NSA and cybersecurity corridor, NIH in Bethesda, and the port of Baltimore anchoring distinct market segments. Suburban Maryland commands premium prices for DC commuter access, while Baltimore City presents some of the East Coast's most compelling value-add investment opportunities with the nation's highest spread between gross yield and net return.",
  MA: "Massachusetts housing combines the nation's most prestigious university cluster (MIT, Harvard, 120+ colleges) with the highest concentration of biotech and life sciences employment. Greater Boston's market is defined by structural undersupply, driving consistent long-term appreciation despite high entry prices. Western Massachusetts offers dramatically different economics — Springfield and Worcester present affordability windows for investors who can underwrite the region's distinct economic base.",
  MI: "Michigan's housing market spans the full investment spectrum — from Detroit's unprecedented value-add opportunities with some of the nation's highest gross yields to Ann Arbor's premium university market and Grand Rapids' consistent appreciation driven by West Michigan's diversified manufacturing base. PropertyIQ tracks the ongoing Detroit metro revitalization trajectory, identifying neighborhoods where fundamentals support sustained recovery versus speculative pricing.",
  MN: "Minnesota's housing market is anchored by the Twin Cities' strong corporate economy (Target, Best Buy, UnitedHealth, 3M), which provides the employment stability that drives consistent residential demand. Minneapolis-Saint Paul's housing market benefits from a diversified economic base largely insulated from single-sector downturns. Duluth and Rochester offer distinct dynamics — a Lake Superior tourism economy and a Mayo Clinic-anchored medical city respectively.",
  MS: "Mississippi offers the nation's most affordable housing market by median price, creating compelling entry points for investors targeting cash flow over appreciation. Gulf Coast markets (Biloxi, Gulfport) blend gaming economy employment with coastal lifestyle demand. The Jackson metro has struggled with population loss and infrastructure challenges that PropertyIQ's Market Health score flags as significant risk factors relative to the state's opportunity markets.",
  MO: "Missouri's housing market presents a tale of two gateway cities — Kansas City's dynamic corporate economy and St. Louis's anchor of healthcare, aerospace, and financial services. Both metros offer value propositions well below Sun Belt competitors despite comparable employment bases. Missouri's pro-landlord legal environment and moderate property tax rates make it a structurally attractive state for buy-and-hold real estate investors.",
  MT: "Montana has experienced some of the nation's most dramatic appreciation as remote workers and second-home buyers have repriced markets from Bozeman to Whitefish. PropertyIQ tracks the growing divergence between Montana markets driven by sustainable job growth (Bozeman's tech corridor) and those reliant on speculative second-home demand vulnerable to rate cycles. Land availability and municipal water infrastructure are critical constraints PropertyIQ factors into its growth capacity assessments.",
  NE: "Nebraska's housing market is anchored by Omaha's insurance, financial services, and logistics economy — home to Berkshire Hathaway, Mutual of Omaha, and Union Pacific. The market has absorbed significant corporate relocations and offers Midwest affordability with major metro amenities. Lincoln's University of Nebraska provides stable rental demand, while Nebraska's agricultural economy insulates smaller markets from tech-sector volatility.",
  NV: "Nevada's housing market is defined by its two dramatically different economies — Las Vegas's entertainment, hospitality, and convention business, and Reno's emergence as a logistics and manufacturing hub (Tesla Gigafactory, Apple, Google). Nevada's zero state income tax and proximity to California drive persistent in-migration. PropertyIQ closely monitors Las Vegas's sensitivity to hospitality sector employment cycles that create volatility not visible in price-only analysis.",
  NH: "New Hampshire combines New England quality of life with no income tax and no sales tax, making it a magnet for Massachusetts and Vermont residents seeking to reduce their tax burden. The southern tier (Manchester, Nashua, Portsmouth) functions as a Boston exurb with strong price appreciation. New Hampshire's limited supply pipeline and strong employment in high-value manufacturing and defense create persistent demand conditions.",
  NJ: "New Jersey's housing market operates in the shadow of New York City's financial economy, serving as the primary affordable alternative for Manhattan and Brooklyn workers. The state's property tax burden — the highest in the nation — is the dominant factor PropertyIQ incorporates into its New Jersey investment return calculations. Northern NJ's proximity to Manhattan commands a sustained premium, while Shore markets blend year-round residents with seasonal demand.",
  NM: "New Mexico's housing market centers on Albuquerque's government, military (Kirtland, White Sands), and university employment alongside the Santa Fe premium market driven by arts, government, and tourism. Albuquerque offers cash flow opportunities with gross yields rarely available in comparable-sized metros. PropertyIQ tracks New Mexico's water rights constraints and climate risk factors as long-term market fundamentals for investors with extended hold periods.",
  NY: "New York State's housing market spans the most expensive urban neighborhoods on Earth (Manhattan) to some of the Midwest's most affordable small markets (Utica, Binghamton, Elmira). Post-pandemic remote work has repriced the Hudson Valley, North Fork, and Catskills while driving vacancy in some Manhattan rental buildings. PropertyIQ tracks both the luxury recovery in high-end NYC markets and the sustained appreciation in upstate markets absorbing displaced buyers from the city.",
  NC: "North Carolina's Research Triangle (Raleigh-Durham-Chapel Hill) and Charlotte's banking corridor anchor two of the Southeast's fastest-growing metro economies. The state's combination of top-tier universities, major corporate relocations (Apple, Google, Amazon in RTP), and relative affordability drives persistent domestic in-migration. Smaller markets like Wilmington, Asheville, and Greensboro each offer distinct investment profiles that PropertyIQ scores independently.",
  ND: "North Dakota's housing market is heavily influenced by oil and gas cycle economics, particularly in the Williston Basin (Bakken formation). Fargo's agricultural services, healthcare, and university economy provides more stable demand insulated from commodity cycles. PropertyIQ's North Dakota scoring specifically models energy sector employment sensitivity for markets in the western half of the state where boom-bust cycles have historically created dramatic price swings.",
  OH: "Ohio's housing market offers some of the Midwest's strongest value propositions across a diverse set of metropolitan economies — Columbus's state government, The Ohio State, and tech growth; Cleveland's healthcare (Cleveland Clinic, University Hospitals) and manufacturing heritage; Cincinnati's consumer goods (P&G, Kroger) and financial services; and Dayton's aerospace and defense. Each metro trades at a fraction of coastal comparables with comparable economic fundamentals.",
  OK: "Oklahoma's housing market benefits from energy sector wealth, agriculture, and tribal economic development alongside a low cost of living. Oklahoma City and Tulsa offer cash flow-positive investment opportunities that rarely appear in Sun Belt markets of comparable size. PropertyIQ tracks Oklahoma's energy price sensitivity — oil and natural gas employment cycles create predictable waves of housing demand that disciplined investors can time using PropertyIQ's Market Health indicators.",
  OR: "Oregon's housing market spans the high-cost tech-driven Portland metro to the rugged outdoor lifestyle markets of Bend and Ashland. Portland's tech employment (Nike, Intel, Adidas) drives strong wage growth, but supply constraints and tenant protection laws create unique investment underwriting requirements that PropertyIQ factors into its InvestorEdge scoring. Central Oregon's Bend market has become a national benchmark for remote-work migration pricing.",
  PA: "Pennsylvania's housing market spans Philadelphia's dense urban neighborhoods and suburban Delaware Valley commuter towns to Pittsburgh's tech renaissance and rural Appalachian communities in between. Philadelphia offers some of the East Coast's strongest cash flow opportunities while Pittsburgh's healthcare, education, and technology cluster (Carnegie Mellon, UPMC) continues to attract population from other Rust Belt metros. Pennsylvania's transfer taxes are among the highest nationally — a factor PropertyIQ incorporates into acquisition cost calculations.",
  RI: "Rhode Island's housing market operates as a Boston satellite, with Providence offering dramatically lower prices than Greater Boston for workers who can commute or work remotely. The state's universities (Brown, RISD, URI) provide stable rental demand anchors. Providence's downtown revitalization and waterfront development have driven appreciation that PropertyIQ's historical scoring models validated against actual market outcomes.",
  SC: "South Carolina's housing market has benefited enormously from domestic migration, particularly retirees (Myrtle Beach, Hilton Head, the Lowcountry) and corporate relocations to Charleston and Greenville. The BMW manufacturing hub in Spartanburg County anchors sustained industrial employment demand. Charleston has become one of the South's most competitive housing markets, with limited buildable land creating structural supply constraints that support long-term appreciation.",
  SD: "South Dakota's zero state income tax and zero personal property tax environment has made it attractive to wealthy individuals seeking tax-advantaged domicile, creating a distinct luxury demand segment in Rapid City and the Black Hills. Sioux Falls anchors the state's most liquid housing market with a diversified financial services economy (Citibank, Wells Fargo). The state's agricultural economy provides stability uncorrelated with coastal market cycles.",
  TN: "Tennessee's housing market has experienced transformational demand from corporate relocations (Oracle, AllianceBernstein, Amazon), domestic migration seeking no state income tax, and a booming tourism economy anchored by Nashville's music and entertainment industry. Memphis offers some of the South's highest cash flow yields for investors, while Chattanooga has emerged as a remote-work destination given its gigabit fiber infrastructure and outdoor lifestyle positioning.",
  TX: "Texas has been the nation's most significant beneficiary of corporate relocation activity, with Oracle, Tesla, HP, and dozens of financial services firms establishing Texas headquarters. The state's no income tax environment, business-friendly regulatory climate, and relatively affordable land have driven explosive population growth. PropertyIQ tracks the diverging performance within Texas — from overheated Austin prices correcting back toward equilibrium to San Antonio and Houston markets absorbing sustained population growth without the same bubble dynamics.",
  UT: "Utah's housing market is shaped by a uniquely young demographic profile (the nation's highest birth rate), the Mormon cultural concentration driving family formation demand, and Salt Lake City's emergence as a major technology hub (Adobe, Qualtrics, Pluralsight). The Wasatch Front's geographic constraints — mountains to the east, lake and desert to the west — create severe supply limitations that PropertyIQ's growth capacity models treat as a permanent structural factor.",
  VT: "Vermont's housing market has been transformed by remote work, with Burlington and Stowe attracting a new wave of buyers from Boston, New York, and beyond who value outdoor recreation access and quality of life. The state's limited developable land and strict Act 250 environmental permitting create structural supply constraints. Vermont's ski resort proximity creates a dual-market dynamic where seasonal rental potential meaningfully augments long-term investment yield calculations.",
  VA: "Virginia's housing market benefits from the nation's largest concentration of federal government employment and defense contracting (Booz Allen Hamilton, Leidos, SAIC, Northrop Grumman). Northern Virginia commands premium prices for DC metro access, while Richmond has emerged as an independent financial services hub attracting migration from more expensive coastal metros. Virginia Beach and Hampton Roads' military economy provides stable, recession-resistant demand across multiple branches of service.",
  WA: "Washington State's housing market is heavily influenced by Seattle's technology economy — Microsoft, Amazon, Boeing, and their supplier ecosystems drive among the nation's highest concentration of six-figure employment. Tacoma and Olympia absorb overflow demand from Seattle-priced-out buyers. The state's lack of income tax (partially offset by a higher sales tax) is a persistent draw for California and Oregon relocators. PropertyIQ tracks hiring cycle sensitivity in Amazon and Microsoft that creates identifiable lead indicators for Seattle housing demand.",
  WV: "West Virginia offers the nation's lowest median home prices among all states, creating extreme cash flow opportunities for investors willing to underwrite the state's demographic challenges. Morgantown (West Virginia University) provides a stable anchor market insulated from the broader statewide population decline. PropertyIQ's Market Health scores for West Virginia explicitly flag the challenging demographic fundamentals while identifying the specific markets where underlying demand conditions support positive investment outcomes.",
  WI: "Wisconsin's housing market combines genuine affordability with a diversified economy spanning manufacturing (Harley-Davidson, Johnson Controls, Oshkosh Corp), agriculture, healthcare, and three major research universities. Milwaukee is undergoing sustained downtown revitalization driven by healthcare anchors (Froedtert, Aurora) and the arts community. Madison's high education attainment and Big Ten anchor create premium pricing relative to other Wisconsin markets.",
  WY: "Wyoming's housing market is dominated by energy sector economics, ranching wealth, and an outdoor lifestyle premium that attracts affluent second-home buyers to Jackson Hole. Cheyenne anchors the state's most populated and economically diversified metro, with federal employment (F.E. Warren AFB) providing stability. Wyoming's zero state income tax creates consistent interest from high-net-worth individuals seeking tax-advantaged real estate portfolios.",
  PR: "Puerto Rico's housing market presents unique opportunities shaped by Act 60 tax incentives (formerly Acts 20 and 22), which have attracted significant mainland investor interest in San Juan's Condado and Dorado Beach communities. PropertyIQ tracks the divergence between this incentive-driven premium segment and the broader island market, which continues to navigate post-hurricane recovery and demographic challenges from net out-migration to the US mainland.",
};

/** Opening paragraph templates keyed by investment profile type */
const OPENING_TEMPLATES = [
  (state: string) =>
    `The ${state} housing market offers investors and homebuyers a diverse range of opportunities across metro areas, counties, and communities at every price point. PropertyIQ analyzes every market in ${state} using 40+ economic, demographic, and housing indicators — generating predictive scores that show where values and investment returns are heading over the next one to three years.`,
  (state: string) =>
    `Finding the best cities to invest in ${state} requires going beyond headline price figures. PropertyIQ's AI-powered platform scores every metropolitan area and county in ${state} using machine learning models validated against six years of actual market outcomes — identifying which markets are undervalued, which are overheated, and which offer the strongest risk-adjusted returns.`,
  (state: string) =>
    `${state}'s real estate market spans a wide range of economic conditions, demographics, and investment profiles. Whether you're a first-time buyer looking for the most affordable ${state} metros or an investor targeting the highest-yield markets, PropertyIQ's data-driven scores give you an analytical edge based on 40+ market indicators updated monthly.`,
];

const CLOSING_TEMPLATES = [
  (state: string) =>
    `Explore PropertyIQ's interactive map to compare all ${state} markets on a single view, or browse individual metro and county pages for detailed analytics, AI-generated market reports, and historical trend data. Sign up free to access PropertyIQ's full scoring dashboard for every ${state} market.`,
  (state: string) =>
    `Use PropertyIQ's scores and interactive analytics to find the right ${state} market for your goals. Compare metros side-by-side, explore county-level data for granular insights, or use the Graphs tool to track historical trends for any ${state} market over time.`,
  (state: string) =>
    `View the full PropertyIQ dashboard for any ${state} market — including HomeReady, InvestorEdge, and Market Health scores updated monthly. Compare ${state} markets against national benchmarks or against each other to identify the best opportunities aligned with your investment strategy.`,
];

function hashState(abbrev: string): number {
  let h = 0;
  for (let i = 0; i < abbrev.length; i++) {
    h = (h << 5) - h + abbrev.charCodeAt(i);
    h |= 0;
  }
  return Math.abs(h);
}

export interface StateSeoContent {
  opening: string;
  economic: string;
  closing: string;
}

export function generateStateSeoContent(
  abbrev: string,
  name: string,
): StateSeoContent {
  const h = hashState(abbrev);
  const openingIdx = h % OPENING_TEMPLATES.length;
  const closingIdx = (h >> 2) % CLOSING_TEMPLATES.length;

  return {
    opening: OPENING_TEMPLATES[openingIdx](name),
    economic:
      STATE_ECONOMIC_CONTEXT[abbrev] ||
      `${name}'s housing market offers diverse opportunities across its metro areas and counties. PropertyIQ tracks all ${name} markets using AI-powered scoring to help investors and homebuyers find the right opportunities.`,
    closing: CLOSING_TEMPLATES[closingIdx](name),
  };
}
