
export interface MetricConfig {
    id: string;
    name: string;
    shortName: string;
    description: string;
    category: string;
    subcategory?: string;

    // Data source
    apiEndpoint: string;
    tableName: string;
    valueField: string;

    // Display
    format: 'currency' | 'percent' | 'number' | 'decimal' | 'years' | 'days' | 'ratio' | 'index';
    precision: number;
    prefix?: string;
    suffix?: string;

    // Chart
    chartType: 'line' | 'area' | 'bar';
    colorScale: 'red-green' | 'green-red' | 'neutral'; // red-green = higher is better
    showAverage: boolean;
    showTrendline: boolean;

    // Geography availability
    geoLevels: ('national' | 'state' | 'metro' | 'county' | 'zip' | 'city')[];

    // Time series
    frequency: 'monthly' | 'quarterly' | 'annual';
    historyStart?: string; // e.g., '2000-01-01'
}

export const METRIC_REGISTRY: Record<string, MetricConfig> = {
    // ============ HOME VALUES ============
    zhvi: {
        id: 'zhvi',
        name: 'Zillow Home Value Index',
        shortName: 'Home Value',
        description: 'Typical home value for mid-tier homes (35th-65th percentile)',
        category: 'Home Price & Affordability',
        apiEndpoint: '/api/v1/zillow/zhvi',
        tableName: 'zillow_zhvi',
        valueField: 'value',
        format: 'currency',
        precision: 0,
        chartType: 'line',
        colorScale: 'neutral',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['national', 'state', 'metro', 'county', 'zip'],
        frequency: 'monthly',
        historyStart: '2000-01-31',
    },

    zhvf_mom: {
        id: 'zhvf_mom',
        name: 'Home Value Forecast (MoM)',
        shortName: 'Forecast MoM%',
        description: 'Month-over-month home value forecast',
        category: 'Home Price & Affordability',
        apiEndpoint: '/api/v1/zillow/forecast',
        tableName: 'zillow_zhvf',
        valueField: 'mom_change',
        format: 'percent',
        precision: 2,
        chartType: 'bar',
        colorScale: 'red-green',
        showAverage: true,
        showTrendline: false,
        geoLevels: ['metro', 'zip'],
        frequency: 'monthly',
    },

    zhvf_yoy: {
        id: 'zhvf_yoy',
        name: 'Home Value Forecast (YoY)',
        shortName: 'Forecast YoY%',
        description: 'Year-over-year home value forecast',
        category: 'Home Price & Affordability',
        apiEndpoint: '/api/v1/zillow/forecast',
        tableName: 'zillow_zhvf',
        valueField: 'yoy_change',
        format: 'percent',
        precision: 2,
        chartType: 'line',
        colorScale: 'red-green',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro', 'zip'],
        frequency: 'monthly',
    },

    median_list_price: {
        id: 'median_list_price',
        name: 'Median List Price',
        shortName: 'List Price',
        description: 'Median price at which homes are listed',
        category: 'Home Price & Affordability',
        apiEndpoint: '/api/v1/zillow/median-list-price',
        tableName: 'zillow_median_list_price_metro',
        valueField: 'value',
        format: 'currency',
        precision: 0,
        chartType: 'line',
        colorScale: 'neutral',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    median_sale_price: {
        id: 'median_sale_price',
        name: 'Median Sale Price',
        shortName: 'Sale Price',
        description: 'Median price at which homes sold',
        category: 'Home Price & Affordability',
        apiEndpoint: '/api/v1/zillow/median-sale-price',
        tableName: 'zillow_median_sale_price_metro',
        valueField: 'value',
        format: 'currency',
        precision: 0,
        chartType: 'line',
        colorScale: 'neutral',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    affordable_price: {
        id: 'affordable_price',
        name: 'Affordable Home Price',
        shortName: 'Affordable Price',
        description: 'Home price affordable to median household (30% rule, 20% down)',
        category: 'Home Price & Affordability',
        apiEndpoint: '/api/v1/zillow/affordability/affordable-price',
        tableName: 'zillow_affordable_price_metro',
        valueField: 'value',
        format: 'currency',
        precision: 0,
        chartType: 'line',
        colorScale: 'red-green', // higher = more affordable market
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    homeowner_income_needed: {
        id: 'homeowner_income_needed',
        name: 'Income Needed to Buy',
        shortName: 'Income Needed',
        description: 'Annual income to afford typical home (30% of income)',
        category: 'Home Price & Affordability',
        apiEndpoint: '/api/v1/zillow/affordability/homeowner-income-needed',
        tableName: 'zillow_homeowner_income_needed_metro',
        valueField: 'value',
        format: 'currency',
        precision: 0,
        chartType: 'line',
        colorScale: 'green-red', // lower = more affordable
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    homeowner_affordability: {
        id: 'homeowner_affordability',
        name: 'Homeowner Affordability',
        shortName: 'Affordability %',
        description: 'Share of income spent on housing for new homeowners',
        category: 'Home Price & Affordability',
        apiEndpoint: '/api/v1/zillow/affordability/homeowner-affordability',
        tableName: 'zillow_homeowner_affordability_metro',
        valueField: 'value',
        format: 'percent',
        precision: 1,
        chartType: 'line',
        colorScale: 'green-red', // lower = more affordable
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    years_to_save: {
        id: 'years_to_save',
        name: 'Years to Save',
        shortName: 'Years to Save',
        description: 'Years to save for 20% down payment at 10% savings rate',
        category: 'Home Price & Affordability',
        apiEndpoint: '/api/v1/zillow/affordability/years-to-save',
        tableName: 'zillow_years_to_save_metro',
        valueField: 'value',
        format: 'years',
        precision: 1,
        suffix: ' years',
        chartType: 'line',
        colorScale: 'green-red', // lower = easier to save
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    renter_income_needed: {
        id: 'renter_income_needed',
        name: 'Income Needed to Rent',
        shortName: 'Renter Income',
        description: 'Annual income to afford typical rental (30% of income)',
        category: 'Home Price & Affordability',
        apiEndpoint: '/api/v1/zillow/affordability/renter-income-needed',
        tableName: 'zillow_renter_income_needed_metro',
        valueField: 'value',
        format: 'currency',
        precision: 0,
        chartType: 'line',
        colorScale: 'green-red',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    renter_affordability: {
        id: 'renter_affordability',
        name: 'Renter Affordability',
        shortName: 'Rent Afford %',
        description: 'Share of income spent on housing for new renters',
        category: 'Home Price & Affordability',
        apiEndpoint: '/api/v1/zillow/affordability/renter-affordability',
        tableName: 'zillow_renter_affordability_metro',
        valueField: 'value',
        format: 'percent',
        precision: 1,
        chartType: 'line',
        colorScale: 'green-red',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    // ============ MARKET TRENDS - SUPPLY ============
    inventory: {
        id: 'inventory',
        name: 'For-Sale Inventory',
        shortName: 'Inventory',
        description: 'Count of active listings in a given month',
        category: 'Market Trends',
        subcategory: 'Supply',
        apiEndpoint: '/api/v1/zillow/inventory',
        tableName: 'zillow_inventory_metro',
        valueField: 'value',
        format: 'number',
        precision: 0,
        chartType: 'area',
        colorScale: 'neutral',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    new_listings: {
        id: 'new_listings',
        name: 'New Listings',
        shortName: 'New Listings',
        description: 'New listings coming on market each month',
        category: 'Market Trends',
        subcategory: 'Supply',
        apiEndpoint: '/api/v1/zillow/new-listings',
        tableName: 'zillow_new_listings_metro',
        valueField: 'value',
        format: 'number',
        precision: 0,
        chartType: 'bar',
        colorScale: 'neutral',
        showAverage: true,
        showTrendline: false,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    new_con_sales_count: {
        id: 'new_con_sales_count',
        name: 'New Construction Sales',
        shortName: 'New Con Sales',
        description: 'Number of new construction homes sold',
        category: 'Market Trends',
        subcategory: 'Supply',
        apiEndpoint: '/api/v1/zillow/new-construction',
        tableName: 'zillow_new_con_sales_count_metro',
        valueField: 'value',
        format: 'number',
        precision: 0,
        chartType: 'bar',
        colorScale: 'neutral',
        showAverage: true,
        showTrendline: false,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    new_con_sale_price: {
        id: 'new_con_sale_price',
        name: 'New Construction Price',
        shortName: 'New Con Price',
        description: 'Median sale price of new construction',
        category: 'Market Trends',
        subcategory: 'Supply',
        apiEndpoint: '/api/v1/zillow/new-construction',
        tableName: 'zillow_new_con_sale_price_metro',
        valueField: 'value',
        format: 'currency',
        precision: 0,
        chartType: 'line',
        colorScale: 'neutral',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    new_con_price_sqft: {
        id: 'new_con_price_sqft',
        name: 'New Construction $/Sqft',
        shortName: 'New Con $/Sqft',
        description: 'Median price per square foot for new construction',
        category: 'Market Trends',
        subcategory: 'Supply',
        apiEndpoint: '/api/v1/zillow/new-construction',
        tableName: 'zillow_new_con_price_sqft_metro',
        valueField: 'value',
        format: 'currency',
        precision: 0,
        prefix: '$',
        suffix: '/sqft',
        chartType: 'line',
        colorScale: 'neutral',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    // ============ MARKET TRENDS - VELOCITY ============
    pending_listings: {
        id: 'pending_listings',
        name: 'Newly Pending Listings',
        shortName: 'Pending',
        description: 'Listings that went pending in a given month',
        category: 'Market Trends',
        subcategory: 'Velocity',
        apiEndpoint: '/api/v1/zillow/pending-listings',
        tableName: 'zillow_pending_listings_metro',
        valueField: 'value',
        format: 'number',
        precision: 0,
        chartType: 'bar',
        colorScale: 'red-green', // higher = more demand
        showAverage: true,
        showTrendline: false,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    days_to_pending: {
        id: 'days_to_pending',
        name: 'Days to Pending',
        shortName: 'Days to Pending',
        description: 'Average days from listing to pending status',
        category: 'Market Trends',
        subcategory: 'Velocity',
        apiEndpoint: '/api/v1/zillow/days-to-pending',
        tableName: 'zillow_days_to_pending_metro',
        valueField: 'value',
        format: 'days',
        precision: 0,
        suffix: ' days',
        chartType: 'line',
        colorScale: 'green-red', // lower = faster market
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    days_to_close: {
        id: 'days_to_close',
        name: 'Days to Close',
        shortName: 'Days to Close',
        description: 'Median days from pending to sale',
        category: 'Market Trends',
        subcategory: 'Velocity',
        apiEndpoint: '/api/v1/zillow/days-to-close',
        tableName: 'zillow_days_to_close_metro',
        valueField: 'value',
        format: 'days',
        precision: 0,
        suffix: ' days',
        chartType: 'line',
        colorScale: 'green-red',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    sales_count: {
        id: 'sales_count',
        name: 'Sales Count',
        shortName: 'Sales',
        description: 'Estimated number of homes sold (nowcast)',
        category: 'Market Trends',
        subcategory: 'Velocity',
        apiEndpoint: '/api/v1/zillow/sales-count',
        tableName: 'zillow_sales_count_metro',
        valueField: 'value',
        format: 'number',
        precision: 0,
        chartType: 'bar',
        colorScale: 'neutral',
        showAverage: true,
        showTrendline: false,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    // ============ MARKET TRENDS - PRICING DYNAMICS ============
    sale_to_list: {
        id: 'sale_to_list',
        name: 'Sale-to-List Ratio',
        shortName: 'Sale/List',
        description: 'Ratio of sale price to final list price',
        category: 'Market Trends',
        subcategory: 'Pricing Dynamics',
        apiEndpoint: '/api/v1/zillow/sale-to-list',
        tableName: 'zillow_sale_to_list_metro',
        valueField: 'value',
        format: 'percent',
        precision: 2,
        chartType: 'line',
        colorScale: 'red-green', // higher = seller's market
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    price_cut_share: {
        id: 'price_cut_share',
        name: 'Share with Price Cut',
        shortName: 'Price Cut %',
        description: 'Percentage of listings with a price reduction',
        category: 'Market Trends',
        subcategory: 'Pricing Dynamics',
        apiEndpoint: '/api/v1/zillow/price-cuts',
        tableName: 'zillow_price_cut_share_metro',
        valueField: 'value',
        format: 'percent',
        precision: 1,
        chartType: 'line',
        colorScale: 'green-red', // lower = stronger market
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    price_cut_amt: {
        id: 'price_cut_amt',
        name: 'Median Price Cut ($)',
        shortName: 'Cut Amount',
        description: 'Median dollar amount of price reductions',
        category: 'Market Trends',
        subcategory: 'Pricing Dynamics',
        apiEndpoint: '/api/v1/zillow/price-cuts',
        tableName: 'zillow_price_cut_amt_metro',
        valueField: 'value',
        format: 'currency',
        precision: 0,
        chartType: 'bar',
        colorScale: 'green-red', // lower = stronger market
        showAverage: true,
        showTrendline: false,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    price_cut_pct: {
        id: 'price_cut_pct',
        name: 'Median Price Cut (%)',
        shortName: 'Cut %',
        description: 'Median percentage of price reductions',
        category: 'Market Trends',
        subcategory: 'Pricing Dynamics',
        apiEndpoint: '/api/v1/zillow/price-cuts',
        tableName: 'zillow_price_cut_pct_metro',
        valueField: 'value',
        format: 'percent',
        precision: 2,
        chartType: 'line',
        colorScale: 'green-red',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    market_heat: {
        id: 'market_heat',
        name: 'Market Heat Index',
        shortName: 'Heat Index',
        description: 'Overall market temperature indicator',
        category: 'Market Trends',
        subcategory: 'Pricing Dynamics',
        apiEndpoint: '/api/v1/zillow/market-heat',
        tableName: 'zillow_market_heat_metro',
        valueField: 'value',
        format: 'index',
        precision: 1,
        chartType: 'area',
        colorScale: 'red-green', // higher = hotter market
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    // ============ RENTALS ============
    zori: {
        id: 'zori',
        name: 'Zillow Observed Rent Index',
        shortName: 'Rent Index',
        description: 'Typical observed market rate rent',
        category: 'Rentals',
        apiEndpoint: '/api/v1/zillow/zori',
        tableName: 'zillow_zori',
        valueField: 'value',
        format: 'currency',
        precision: 0,
        suffix: '/mo',
        chartType: 'line',
        colorScale: 'neutral',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro', 'zip', 'county', 'city'],
        frequency: 'monthly',
    },

    zordi: {
        id: 'zordi',
        name: 'Rental Demand Index',
        shortName: 'Rental Demand',
        description: 'Rental market engagement proxy based on Zillow listing activity',
        category: 'Rentals',
        apiEndpoint: '/api/v1/zillow/zordi',
        tableName: 'zillow_zordi_metro',
        valueField: 'value',
        format: 'index',
        precision: 1,
        chartType: 'line',
        colorScale: 'red-green', // higher = more demand
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro'],
        frequency: 'monthly',
    },

    // ============ INVESTOR METRICS (Calculated) ============
    gross_rent_multiplier: {
        id: 'gross_rent_multiplier',
        name: 'Gross Rent Multiplier',
        shortName: 'GRM',
        description: 'Home value divided by annual rent (lower = better for investors)',
        category: 'Investor Metrics',
        apiEndpoint: '/api/v1/metrics/grm',
        tableName: 'calculated_metrics',
        valueField: 'grm',
        format: 'decimal',
        precision: 1,
        suffix: 'x',
        chartType: 'line',
        colorScale: 'green-red', // lower = better investment
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro', 'zip'],
        frequency: 'monthly',
    },

    rent_price_ratio: {
        id: 'rent_price_ratio',
        name: 'Rent/Price Ratio',
        shortName: 'Rent/Price',
        description: 'Annual rent as percentage of home value',
        category: 'Investor Metrics',
        apiEndpoint: '/api/v1/metrics/rent-price-ratio',
        tableName: 'calculated_metrics',
        valueField: 'rent_price_ratio',
        format: 'percent',
        precision: 2,
        chartType: 'line',
        colorScale: 'red-green', // higher = better cash flow
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro', 'zip'],
        frequency: 'monthly',
    },

    cap_rate_proxy: {
        id: 'cap_rate_proxy',
        name: 'Cap Rate Proxy',
        shortName: 'Cap Rate',
        description: 'Estimated cap rate based on rent/price ratio (simplified)',
        category: 'Investor Metrics',
        apiEndpoint: '/api/v1/metrics/cap-rate',
        tableName: 'calculated_metrics',
        valueField: 'cap_rate',
        format: 'percent',
        precision: 2,
        chartType: 'line',
        colorScale: 'red-green', // higher = better return
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro', 'zip'],
        frequency: 'monthly',
    },

    // ============ PROPERTYIQ SCORES ============
    piq_overall: {
        id: 'piq_overall',
        name: 'PropertyIQ Overall Score',
        shortName: 'Overall',
        description: 'Composite score across all factors',
        category: 'PropertyIQ Scores',
        apiEndpoint: '/api/v1/scores/overall',
        tableName: 'propertyiq_scores',
        valueField: 'overall_score',
        format: 'number',
        precision: 0,
        chartType: 'line',
        colorScale: 'red-green',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro', 'county', 'zip'],
        frequency: 'monthly',
    },

    piq_value: {
        id: 'piq_value',
        name: 'Value Score',
        shortName: 'Value',
        description: 'Score based on price vs. fundamentals',
        category: 'PropertyIQ Scores',
        apiEndpoint: '/api/v1/scores/value',
        tableName: 'propertyiq_scores',
        valueField: 'value_score',
        format: 'number',
        precision: 0,
        chartType: 'line',
        colorScale: 'red-green',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro', 'county', 'zip'],
        frequency: 'monthly',
    },

    piq_momentum: {
        id: 'piq_momentum',
        name: 'Momentum Score',
        shortName: 'Momentum',
        description: 'Score based on market velocity indicators',
        category: 'PropertyIQ Scores',
        apiEndpoint: '/api/v1/scores/momentum',
        tableName: 'propertyiq_scores',
        valueField: 'momentum_score',
        format: 'number',
        precision: 0,
        chartType: 'line',
        colorScale: 'red-green',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro', 'county', 'zip'],
        frequency: 'monthly',
    },

    piq_cashflow: {
        id: 'piq_cashflow',
        name: 'Cash Flow Score',
        shortName: 'Cash Flow',
        description: 'Score based on rental income potential',
        category: 'PropertyIQ Scores',
        apiEndpoint: '/api/v1/scores/cashflow',
        tableName: 'propertyiq_scores',
        valueField: 'cashflow_score',
        format: 'number',
        precision: 0,
        chartType: 'line',
        colorScale: 'red-green',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro', 'county', 'zip'],
        frequency: 'monthly',
    },

    piq_risk: {
        id: 'piq_risk',
        name: 'Risk Score',
        shortName: 'Risk',
        description: 'Score based on market stability (higher = lower risk)',
        category: 'PropertyIQ Scores',
        apiEndpoint: '/api/v1/scores/risk',
        tableName: 'propertyiq_scores',
        valueField: 'risk_score',
        format: 'number',
        precision: 0,
        chartType: 'line',
        colorScale: 'red-green', // higher score = lower risk = better
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro', 'county', 'zip'],
        frequency: 'monthly',
    },

    piq_growth: {
        id: 'piq_growth',
        name: 'Growth Score',
        shortName: 'Growth',
        description: 'Score based on appreciation potential',
        category: 'PropertyIQ Scores',
        apiEndpoint: '/api/v1/scores/growth',
        tableName: 'propertyiq_scores',
        valueField: 'growth_score',
        format: 'number',
        precision: 0,
        chartType: 'line',
        colorScale: 'red-green',
        showAverage: true,
        showTrendline: true,
        geoLevels: ['metro', 'county', 'zip'],
        frequency: 'monthly',
    },
};

// Helper to get metrics by category
export const getMetricsByCategory = (category: string): MetricConfig[] => {
    return Object.values(METRIC_REGISTRY).filter(m => m.category === category);
};

// Helper to get metrics by subcategory
export const getMetricsBySubcategory = (category: string, subcategory: string): MetricConfig[] => {
    return Object.values(METRIC_REGISTRY).filter(
        m => m.category === category && m.subcategory === subcategory
    );
};
