/**
 * Gain staging for the PropertyIQ video mix — the ONLY place mix levels
 * may be defined. Every composition type uses these same constants, which
 * is what keeps loudness consistent across formats (narration itself is
 * loudnorm'd to -16 LUFS backend-side before it reaches the composition).
 */
export const AUDIO_LEVELS = {
  /** Narration is the reference level; everything else sits under it. */
  narration: 1.0,
  /** Music bed when nobody is speaking. */
  musicBed: 0.14,
  /** Music bed while narration is active (sidechain-style duck target). */
  musicDucked: 0.045,
  /** Constant ambient layer so silences never sound dead/cut-off. */
  roomTone: 0.04,
  /** Brand sting under the bumper. */
  sting: 0.8,
  /** UI sound effects (whoosh/tick/chime) on entrances. */
  sfx: 0.45,
} as const;

/** Duck envelope shape, in frames at 30fps. */
export const DUCK = {
  /** Music starts dipping this many frames BEFORE speech begins. */
  attackFrames: 8,
  /** Music recovers over this many frames after speech ends. */
  releaseFrames: 20,
  /** Word gaps shorter than this stay ducked (no pumping between words). */
  holdMs: 600,
} as const;

/**
 * Selectable music beds.
 *
 * One bed across an entire channel is an audible tell — viewers who see two
 * of your videos hear the same loop and register "template." Formats pick a
 * default here and a run can override it, so the catalogue can grow without
 * touching any composition.
 *
 * NOTE: only `calm_indigo` ships today (procedurally generated by
 * scripts/generate-audio-assets.mjs). Adding real, licensed tracks is a
 * content task, not a code one — drop the file in public/audio/ and add a
 * line here.
 */
export const MUSIC_BED_NAMES = ["calm_indigo"] as const;

export type MusicBedName = (typeof MUSIC_BED_NAMES)[number];

export const MUSIC_BEDS: Record<MusicBedName, string> = {
  calm_indigo: "audio/music-bed.wav",
};

export const DEFAULT_MUSIC_BED: MusicBedName = "calm_indigo";

export function musicBedPath(name: MusicBedName | undefined): string {
  return MUSIC_BEDS[name ?? DEFAULT_MUSIC_BED] ?? MUSIC_BEDS[DEFAULT_MUSIC_BED];
}

/** Static asset paths under public/ (see scripts/generate-audio-assets.mjs). */
export const AUDIO_ASSETS = {
  roomTone: "audio/room-tone.wav",
  sfx: {
    whoosh: "audio/sfx-whoosh.wav",
    tick: "audio/sfx-tick.wav",
    chime: "audio/sfx-chime.wav",
  },
} as const;

export type SfxName = keyof typeof AUDIO_ASSETS.sfx;
