// packages/backend/src/content-pipeline/infographics/create-infographic-run.ts
import { BadRequestException } from '@nestjs/common';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { CreateRunDto } from '../dto/create-run.dto';
import {
  findInfographicTopic,
  findInfographicTopicTask,
} from './infographic-topics';
import { findInfographicStyle } from './infographic-styles';

export interface CreatedRun {
  id: string;
  idempotencyKey: string;
  status: string;
}

/**
 * Creates an `infographic` run and deliberately leaves it parked at `queued`.
 *
 * Every other format is advanced from here by enqueuing an orchestrator job.
 * Infographics are generated by NotebookLM through the `nlm` CLI, which needs
 * Troy's local Google auth and therefore cannot run on the production backend.
 * So this lane stops at the database: `packages/backend/scripts/infographic-worker.ts`
 * runs locally, claims these rows, and carries them the rest of the way.
 *
 * Parking at `queued` is safe because RecoverStuckRunsCron only scans the
 * statuses listed in its STEP_TIMEOUT_MIN table, and `queued` is not one of
 * them — nothing will re-enqueue or time these out from under the worker.
 */
export async function createInfographicRun(
  client: SupabaseClient,
  dto: CreateRunDto,
): Promise<CreatedRun> {
  const params = dto.infographicParams;
  if (!params) {
    throw new BadRequestException(
      'infographic runs require infographicParams (topic slug, task number, style id)',
    );
  }

  // Re-checked here rather than trusted from the DTO: this function is also
  // reachable from internal callers that never ran the validation pipe.
  const topic = findInfographicTopic(params.topic_slug);
  if (!topic) {
    throw new BadRequestException(`unknown topic slug ${params.topic_slug}`);
  }
  if (!topic.vetted) {
    throw new BadRequestException(
      `topic ${topic.slug} is not vetted yet and cannot be generated from`,
    );
  }
  const task = findInfographicTopicTask(topic, params.task_number);
  if (!task) {
    throw new BadRequestException(
      `topic ${topic.slug} has no task number ${params.task_number}`,
    );
  }
  const style = findInfographicStyle(params.style_id);
  if (!style) {
    throw new BadRequestException(`unknown style id ${params.style_id}`);
  }
  if (!topic.notebookId || !topic.sourceId) {
    throw new BadRequestException(
      `topic ${topic.slug} has no NotebookLM notebook wired up yet`,
    );
  }

  const { data: inserted, error } = await client
    .from('content_runs')
    .insert({
      format: 'infographic',
      // Infographics are product explainers, not market-scoped content.
      audience: 'mixed',
      // market_query is NOT NULL and drives the run list label. Nothing
      // resolves it for this format, so the composer's human label wins when
      // supplied; otherwise derive one.
      market_query: dto.marketQuery?.trim()
        ? dto.marketQuery.trim()
        : `${topic.slug} - ${task.label}`,
      approval_mode: dto.approvalMode ?? 'review',
      selected_platforms: dto.selectedPlatforms ?? [],
      idempotency_key: dto.idempotencyKey,
      batch_id: dto.batchId ?? null,
      format_options: {
        ...(dto.formatOptions ?? {}),
        infographic: {
          topic_slug: topic.slug,
          task_number: task.number,
          style_id: style.id,
        },
      },
      status: 'queued',
      triggered_by: dto.triggeredBy ?? 'manual',
    })
    .select('id, status')
    .single();
  if (error) throw error;

  return {
    id: inserted.id,
    idempotencyKey: dto.idempotencyKey,
    status: inserted.status,
  };
}
